-- Readability copy -- not the artifact a server loads.
--
-- Library.suspicion_of_infection.json in this directory is authoritative. This SQL is
-- the decoded form of its content.data, byte-identical to the sql-text
-- extension beside it. Edit neither: both are generated by
-- `mimic-utils metrics-finalize` from the finalized attempt.

WITH antibiotic_rows AS (
    SELECT
        a.patient_key,
        a.encounter_key,
        a.icu_encounter_key,
        CAST(p.subject_id_str AS INTEGER) AS subject_id,
        CAST(e.hadm_id_str AS INTEGER) AS hadm_id,
        CAST(i.stay_id_str AS INTEGER) AS stay_id,
        a.antibiotic,
        TRY_CAST(a.starttime AS TIMESTAMP_NTZ) AS antibiotic_time,
        CAST(TRY_CAST(a.starttime AS TIMESTAMP_NTZ) AS DATE) AS antibiotic_date,
        TRY_CAST(a.stoptime AS TIMESTAMP_NTZ) AS antibiotic_stoptime
    FROM antibiotic AS a
    INNER JOIN patient AS p
        ON a.patient_key = p.patient_key
    INNER JOIN encounter AS e
        ON a.encounter_key = e.encounter_key
        AND a.patient_key = e.patient_key
    LEFT JOIN encounter_icu AS i
        ON a.icu_encounter_key = i.icu_encounter_key
), ab_tbl AS (
    SELECT
        patient_key,
        encounter_key,
        icu_encounter_key,
        subject_id,
        hadm_id,
        stay_id,
        antibiotic,
        antibiotic_time,
        antibiotic_date,
        antibiotic_stoptime,
        ROW_NUMBER() OVER (
            PARTITION BY subject_id
            ORDER BY
                antibiotic_time NULLS LAST,
                antibiotic_stoptime NULLS LAST,
                antibiotic,
                hadm_id NULLS LAST,
                stay_id NULLS LAST
        ) AS ab_id
    FROM antibiotic_rows
), micro_rows AS (
    SELECT
        s.specimen_key,
        s.patient_key,
        CAST(s.micro_specimen_id_str AS INTEGER) AS micro_specimen_id,
        TRY_CAST(s.collected_datetime AS TIMESTAMP_NTZ) AS charttime,
        s.specimen_type_display,
        t.micro_org_key,
        TRY_CAST(t.effective_datetime AS TIMESTAMP_NTZ) AS test_effective_datetime,
        o.org_code,
        o.org_display
    FROM micro_specimen AS s
    LEFT JOIN micro_test AS t
        ON s.specimen_key = t.specimen_key
    LEFT JOIN micro_org AS o
        ON t.micro_org_key = o.micro_org_key
), me AS (
    SELECT
        specimen_key AS micro_specimen_key,
        MAX(patient_key) AS patient_key,
        MAX(micro_specimen_id) AS micro_specimen_id,
        CAST(
            COALESCE(
                MAX(charttime),
                MAX(test_effective_datetime)
            ) AS DATE
        ) AS chartdate,
        MAX(charttime) AS charttime,
        MAX(specimen_type_display) AS spec_type_desc,
        MAX(
            CASE
                WHEN org_display IS NOT NULL
                    AND org_code <> '90856'
                    AND org_display <> ''
                    THEN 1
                ELSE 0
            END
        ) AS positiveculture
    FROM micro_rows
    GROUP BY specimen_key
), me_then_ab AS (
    SELECT
        ab_tbl.subject_id,
        ab_tbl.hadm_id,
        ab_tbl.stay_id,
        ab_tbl.ab_id,
        ab_tbl.patient_key,
        me72.micro_specimen_id,
        COALESCE(
            me72.charttime,
            CAST(me72.chartdate AS TIMESTAMP_NTZ)
        ) AS last72_charttime,
        me72.positiveculture AS last72_positiveculture,
        me72.spec_type_desc AS last72_specimen,
        ROW_NUMBER() OVER (
            PARTITION BY ab_tbl.subject_id, ab_tbl.ab_id
            ORDER BY
                me72.chartdate,
                me72.charttime NULLS LAST,
                me72.positiveculture DESC,
                me72.micro_specimen_id
        ) AS micro_seq
    FROM ab_tbl
    LEFT JOIN me AS me72
        ON ab_tbl.patient_key = me72.patient_key
        AND (
            (
                me72.charttime IS NOT NULL
                AND ab_tbl.antibiotic_time > me72.charttime
                AND ab_tbl.antibiotic_time <= me72.charttime + INTERVAL 72 HOURS
            )
            OR
            (
                me72.charttime IS NULL
                AND ab_tbl.antibiotic_date >= me72.chartdate
                AND ab_tbl.antibiotic_date <= DATE_ADD(me72.chartdate, 3)
            )
        )
), ab_then_me AS (
    SELECT
        ab_tbl.subject_id,
        ab_tbl.hadm_id,
        ab_tbl.stay_id,
        ab_tbl.ab_id,
        ab_tbl.patient_key,
        me24.micro_specimen_id,
        COALESCE(
            me24.charttime,
            CAST(me24.chartdate AS TIMESTAMP_NTZ)
        ) AS next24_charttime,
        me24.positiveculture AS next24_positiveculture,
        me24.spec_type_desc AS next24_specimen,
        ROW_NUMBER() OVER (
            PARTITION BY ab_tbl.subject_id, ab_tbl.ab_id
            ORDER BY
                me24.chartdate,
                me24.charttime NULLS LAST,
                me24.positiveculture DESC,
                me24.micro_specimen_id
        ) AS micro_seq
    FROM ab_tbl
    LEFT JOIN me AS me24
        ON ab_tbl.patient_key = me24.patient_key
        AND (
            (
                me24.charttime IS NOT NULL
                AND ab_tbl.antibiotic_time >= me24.charttime - INTERVAL 24 HOURS
                AND ab_tbl.antibiotic_time < me24.charttime
            )
            OR
            (
                me24.charttime IS NULL
                AND ab_tbl.antibiotic_date >= DATE_SUB(me24.chartdate, 1)
                AND ab_tbl.antibiotic_date <= me24.chartdate
            )
        )
), selected AS (
    SELECT
        ab_tbl.subject_id,
        ab_tbl.stay_id,
        ab_tbl.hadm_id,
        ab_tbl.ab_id,
        ab_tbl.antibiotic,
        ab_tbl.antibiotic_time,
        CASE
            WHEN me2ab.last72_specimen IS NULL
                AND ab2me.next24_specimen IS NULL
                THEN 0
            ELSE 1
        END AS suspected_infection,
        CASE
            WHEN me2ab.last72_specimen IS NULL
                AND ab2me.next24_specimen IS NULL
                THEN NULL
            ELSE COALESCE(me2ab.last72_charttime, ab_tbl.antibiotic_time)
        END AS suspected_infection_time,
        COALESCE(me2ab.last72_charttime, ab2me.next24_charttime) AS culture_time,
        COALESCE(me2ab.last72_specimen, ab2me.next24_specimen) AS specimen,
        COALESCE(
            me2ab.last72_positiveculture,
            ab2me.next24_positiveculture
        ) AS positive_culture,
        ab_tbl.patient_key,
        ab_tbl.encounter_key,
        ab_tbl.icu_encounter_key
    FROM ab_tbl
    LEFT JOIN ab_then_me AS ab2me
        ON ab_tbl.subject_id = ab2me.subject_id
        AND ab_tbl.ab_id = ab2me.ab_id
        AND ab2me.micro_seq = 1
    LEFT JOIN me_then_ab AS me2ab
        ON ab_tbl.subject_id = me2ab.subject_id
        AND ab_tbl.ab_id = me2ab.ab_id
        AND me2ab.micro_seq = 1
)
SELECT
    CAST(ab_id AS BIGINT) AS ab_id,
    CAST(antibiotic AS VARCHAR(255)) AS antibiotic,
    CAST(antibiotic_time AS TIMESTAMP_NTZ) AS antibiotic_time,
    CAST(suspected_infection AS INTEGER) AS suspected_infection,
    CAST(suspected_infection_time AS TIMESTAMP_NTZ) AS suspected_infection_time,
    CAST(culture_time AS TIMESTAMP_NTZ) AS culture_time,
    CAST(specimen AS VARCHAR(255)) AS specimen,
    CAST(positive_culture AS INTEGER) AS positive_culture,
    patient_key,
    encounter_key,
    icu_encounter_key
FROM selected
;
