-- Readability copy -- not the artifact a server loads.
--
-- Library.ventilation.json in this directory is authoritative. This SQL is
-- the decoded form of its content.data, byte-identical to the sql-text
-- extension beside it. Edit neither: both are generated by
-- `mimic-utils metrics-finalize` from the finalized attempt.

WITH oxygen_events AS (
    SELECT
        od.patient_key,
        od.icu_encounter_key,
        CAST(e.stay_id_str AS INTEGER) AS stay_id,
        od.charttime,
        od.o2_delivery_device_1,
        od.o2_delivery_device_2,
        od.o2_delivery_device_3,
        od.o2_delivery_device_4
    FROM oxygen_delivery AS od
    INNER JOIN ventilation_encounter AS e
        ON od.icu_encounter_key = e.icu_encounter_key
), ventilator_events AS (
    SELECT
        vs.patient_key,
        vs.icu_encounter_key,
        CAST(e.stay_id_str AS INTEGER) AS stay_id,
        vs.charttime,
        vs.ventilator_mode,
        vs.ventilator_mode_hamilton
    FROM ventilator_setting AS vs
    INNER JOIN ventilation_encounter AS e
        ON vs.icu_encounter_key = e.icu_encounter_key
), tm AS (
    SELECT stay_id, charttime
    FROM ventilator_events
    UNION DISTINCT
    SELECT stay_id, charttime
    FROM oxygen_events
), vs AS (
    SELECT
        tm.stay_id,
        tm.charttime,
        COALESCE(vset.patient_key, od.patient_key) AS patient_key,
        COALESCE(vset.icu_encounter_key, od.icu_encounter_key) AS icu_encounter_key,
        od.o2_delivery_device_1,
        od.o2_delivery_device_2,
        od.o2_delivery_device_3,
        od.o2_delivery_device_4,
        COALESCE(vset.ventilator_mode, vset.ventilator_mode_hamilton) AS vent_mode,
        CASE
            WHEN od.o2_delivery_device_1 IN
                (
                    'Tracheostomy tube'
                    , 'Trach mask '
                )
                THEN 'Tracheostomy'
            WHEN od.o2_delivery_device_1 IN
                (
                    'Endotracheal tube'
                )
                OR vset.ventilator_mode IN
                (
                    '(S) CMV'
                    , 'APRV'
                    , 'APRV/Biphasic+ApnPress'
                    , 'APRV/Biphasic+ApnVol'
                    , 'APV (cmv)'
                    , 'Ambient'
                    , 'Apnea Ventilation'
                    , 'CMV'
                    , 'CMV/ASSIST'
                    , 'CMV/ASSIST/AutoFlow'
                    , 'CMV/AutoFlow'
                    , 'CPAP/PPS'
                    , 'CPAP/PSV'
                    , 'CPAP/PSV+Apn TCPL'
                    , 'CPAP/PSV+ApnPres'
                    , 'CPAP/PSV+ApnVol'
                    , 'MMV'
                    , 'MMV/AutoFlow'
                    , 'MMV/PSV'
                    , 'MMV/PSV/AutoFlow'
                    , 'P-CMV'
                    , 'PCV+'
                    , 'PCV+/PSV'
                    , 'PCV+Assist'
                    , 'PRES/AC'
                    , 'PRVC/AC'
                    , 'PRVC/SIMV'
                    , 'PSV/SBT'
                    , 'SIMV'
                    , 'SIMV/AutoFlow'
                    , 'SIMV/PRES'
                    , 'SIMV/PSV'
                    , 'SIMV/PSV/AutoFlow'
                    , 'SIMV/VOL'
                    , 'SYNCHRON MASTER'
                    , 'SYNCHRON SLAVE'
                    , 'VOL/AC'
                )
                OR vset.ventilator_mode_hamilton IN
                (
                    'APRV'
                    , 'APV (cmv)'
                    , 'Ambient'
                    , '(S) CMV'
                    , 'P-CMV'
                    , 'SIMV'
                    , 'APV (simv)'
                    , 'P-SIMV'
                    , 'VS'
                    , 'ASV'
                )
                THEN 'InvasiveVent'
            WHEN od.o2_delivery_device_1 IN
                (
                    'Bipap mask '
                    , 'CPAP mask '
                )
                OR od.o2_delivery_device_2 IN ('Bipap mask ', 'CPAP mask ')
                OR od.o2_delivery_device_3 IN ('Bipap mask ', 'CPAP mask ')
                OR od.o2_delivery_device_4 IN ('Bipap mask ', 'CPAP mask ')
                OR vset.ventilator_mode_hamilton IN
                (
                    'DuoPaP'
                    , 'NIV'
                    , 'NIV-ST'
                )
                THEN 'NonInvasiveVent'
            WHEN od.o2_delivery_device_1 IN
                (
                    'High flow nasal cannula'
                )
                THEN 'HFNC'
            WHEN od.o2_delivery_device_1 IN
                (
                    'Non-rebreather'
                    , 'Face tent'
                    , 'Aerosol-cool'
                    , 'Venti mask '
                    , 'Medium conc mask '
                    , 'Ultrasonic neb'
                    , 'Vapomist'
                    , 'Oxymizer'
                    , 'High flow neb'
                    , 'Nasal cannula'
                )
                THEN 'SupplementalOxygen'
            WHEN od.o2_delivery_device_1 IN
                (
                    'None'
                )
                THEN 'None'
            ELSE NULL
        END AS ventilation_status
    FROM tm
    LEFT JOIN ventilator_events AS vset
        ON tm.stay_id = vset.stay_id
        AND tm.charttime = vset.charttime
    LEFT JOIN oxygen_events AS od
        ON tm.stay_id = od.stay_id
        AND tm.charttime = od.charttime
), vd0 AS (
    SELECT
        stay_id,
        charttime,
        patient_key,
        icu_encounter_key,
        LAG(charttime, 1) OVER (
            PARTITION BY stay_id, ventilation_status
            ORDER BY charttime
        ) AS charttime_lag,
        LEAD(charttime, 1) OVER w AS charttime_lead,
        ventilation_status,
        LAG(ventilation_status, 1) OVER w AS ventilation_status_lag
    FROM vs
    WHERE ventilation_status IS NOT NULL
    WINDOW w AS (PARTITION BY stay_id ORDER BY charttime)
), vd1 AS (
    SELECT
        stay_id,
        charttime,
        patient_key,
        icu_encounter_key,
        charttime_lag,
        charttime_lead,
        ventilation_status,
        CAST(
            TIMESTAMPDIFF(
                MINUTE,
                DATE_TRUNC('MINUTE', charttime_lag),
                DATE_TRUNC('MINUTE', charttime)
            ) AS DOUBLE
        ) / CAST(60 AS DOUBLE) AS ventduration,
        CASE
            WHEN ventilation_status_lag IS NULL THEN 1
            WHEN TIMESTAMPDIFF(
                HOUR,
                DATE_TRUNC('HOUR', charttime_lag),
                DATE_TRUNC('HOUR', charttime)
            ) >= 14 THEN 1
            WHEN ventilation_status_lag != ventilation_status THEN 1
            ELSE 0
        END AS new_ventilation_event
    FROM vd0
), vd2 AS (
    SELECT
        stay_id,
        charttime,
        patient_key,
        icu_encounter_key,
        charttime_lead,
        ventilation_status,
        ventduration,
        new_ventilation_event,
        SUM(new_ventilation_event) OVER (
            PARTITION BY stay_id
            ORDER BY charttime
        ) AS vent_seq
    FROM vd1
), episodes AS (
    SELECT
        stay_id,
        MAX(patient_key) AS patient_key,
        MAX(icu_encounter_key) AS icu_encounter_key,
        MIN(charttime) AS starttime,
        MAX(
            CASE
                WHEN charttime_lead IS NULL
                    OR TIMESTAMPDIFF(
                        HOUR,
                        DATE_TRUNC('HOUR', charttime),
                        DATE_TRUNC('HOUR', charttime_lead)
                    ) >= 14
                    THEN charttime
                ELSE charttime_lead
            END
        ) AS endtime,
        MAX(ventilation_status) AS ventilation_status
    FROM vd2
    GROUP BY stay_id, vent_seq
    HAVING MIN(charttime) != MAX(charttime)
)
SELECT
    CAST(ep.starttime AS TIMESTAMP_NTZ) AS starttime,
    CAST(ep.endtime AS TIMESTAMP_NTZ) AS endtime,
    CAST(ep.ventilation_status AS VARCHAR(255)) AS ventilation_status,
    ep.icu_encounter_key,
    ep.patient_key
FROM episodes AS ep
;
