-- Readability copy -- not the artifact a server loads.
--
-- Library.first_day_sofa.json in this directory is authoritative. This SQL is
-- the decoded form of its content.data, byte-identical to the sql-text
-- extension beside it. Edit neither: both are generated by
-- `mimic-utils metrics-finalize` from the finalized attempt.

WITH icu_stays AS (
    SELECT
        e.icu_encounter_key,
        e.patient_key,
        h.encounter_key,
        p.subject_id_str,
        h.hadm_id_str,
        e.stay_id_str,
        TRY_CAST(e.intime_datetime AS TIMESTAMP_NTZ) AS intime
    FROM icu_encounter AS e
    INNER JOIN patient AS p
        ON e.patient_key = p.patient_key
    LEFT JOIN hospital_encounter AS h
        ON e.encounter_key = h.encounter_key
    WHERE e.stay_system = 'http://mimic.mit.edu/fhir/mimic/identifier/encounter-icu'
        AND e.stay_id_str IS NOT NULL
), vaso_stg AS (
    SELECT i.icu_encounter_key, 'norepinephrine' AS treatment, mv.vaso_rate AS rate
    FROM icu_stays AS i
    INNER JOIN norepinephrine AS mv
        ON i.icu_encounter_key = mv.icu_encounter_key
        AND mv.starttime >= i.intime - INTERVAL 6 HOURS
        AND mv.starttime <= i.intime + INTERVAL 1 DAY
    UNION ALL
    SELECT i.icu_encounter_key, 'epinephrine' AS treatment, mv.vaso_rate AS rate
    FROM icu_stays AS i
    INNER JOIN epinephrine AS mv
        ON i.icu_encounter_key = mv.icu_encounter_key
        AND mv.starttime >= i.intime - INTERVAL 6 HOURS
        AND mv.starttime <= i.intime + INTERVAL 1 DAY
    UNION ALL
    SELECT i.icu_encounter_key, 'dobutamine' AS treatment, mv.vaso_rate AS rate
    FROM icu_stays AS i
    INNER JOIN dobutamine AS mv
        ON i.icu_encounter_key = mv.icu_encounter_key
        AND mv.starttime >= i.intime - INTERVAL 6 HOURS
        AND mv.starttime <= i.intime + INTERVAL 1 DAY
    UNION ALL
    SELECT i.icu_encounter_key, 'dopamine' AS treatment, mv.vaso_rate AS rate
    FROM icu_stays AS i
    INNER JOIN dopamine AS mv
        ON i.icu_encounter_key = mv.icu_encounter_key
        AND mv.starttime >= i.intime - INTERVAL 6 HOURS
        AND mv.starttime <= i.intime + INTERVAL 1 DAY
), vaso_mv AS (
    SELECT
        i.icu_encounter_key,
        MAX(CASE WHEN v.treatment = 'norepinephrine' THEN v.rate ELSE NULL END) AS rate_norepinephrine,
        MAX(CASE WHEN v.treatment = 'epinephrine' THEN v.rate ELSE NULL END) AS rate_epinephrine,
        MAX(CASE WHEN v.treatment = 'dopamine' THEN v.rate ELSE NULL END) AS rate_dopamine,
        MAX(CASE WHEN v.treatment = 'dobutamine' THEN v.rate ELSE NULL END) AS rate_dobutamine
    FROM icu_stays AS i
    LEFT JOIN vaso_stg AS v
        ON i.icu_encounter_key = v.icu_encounter_key
    GROUP BY i.icu_encounter_key
), pafi1 AS (
    SELECT
        i.icu_encounter_key,
        b.charttime,
        b.pao2fio2ratio,
        CASE WHEN vd.icu_encounter_key IS NOT NULL THEN 1 ELSE 0 END AS isvent
    FROM icu_stays AS i
    LEFT JOIN bg AS b
        ON i.patient_key = b.patient_key
        AND b.charttime >= i.intime - INTERVAL 6 HOURS
        AND b.charttime <= i.intime + INTERVAL 1 DAY
        AND b.specimen = 'ART.'
    LEFT JOIN ventilation AS vd
        ON i.icu_encounter_key = vd.icu_encounter_key
        AND b.charttime >= vd.starttime
        AND b.charttime <= vd.endtime
        AND vd.ventilation_status = 'InvasiveVent'
), pafi2 AS (
    SELECT
        icu_encounter_key,
        MIN(CASE WHEN isvent = 0 THEN pao2fio2ratio ELSE NULL END) AS pao2fio2_novent_min,
        MIN(CASE WHEN isvent = 1 THEN pao2fio2ratio ELSE NULL END) AS pao2fio2_vent_min
    FROM pafi1
    GROUP BY icu_encounter_key
), scorecomp AS (
    SELECT
        i.icu_encounter_key,
        v.mbp_min,
        mv.rate_norepinephrine,
        mv.rate_epinephrine,
        mv.rate_dopamine,
        mv.rate_dobutamine,
        l.creatinine_max,
        l.bilirubin_total_max AS bilirubin_max,
        l.platelets_min AS platelet_min,
        pf.pao2fio2_novent_min,
        pf.pao2fio2_vent_min,
        uo.urineoutput,
        gcs.gcs_min
    FROM icu_stays AS i
    LEFT JOIN vaso_mv AS mv
        ON i.icu_encounter_key = mv.icu_encounter_key
    LEFT JOIN pafi2 AS pf
        ON i.icu_encounter_key = pf.icu_encounter_key
    LEFT JOIN first_day_vitalsign AS v
        ON i.icu_encounter_key = v.icu_encounter_key
    LEFT JOIN first_day_lab AS l
        ON i.icu_encounter_key = l.icu_encounter_key
    LEFT JOIN first_day_urine_output AS uo
        ON i.icu_encounter_key = uo.icu_encounter_key
    LEFT JOIN first_day_gcs AS gcs
        ON i.icu_encounter_key = gcs.icu_encounter_key
), scorecalc AS (
    SELECT
        icu_encounter_key,
        CASE
            WHEN pao2fio2_vent_min < 100 THEN 4
            WHEN pao2fio2_vent_min < 200 THEN 3
            WHEN pao2fio2_novent_min < 300 THEN 2
            WHEN pao2fio2_novent_min < 400 THEN 1
            WHEN COALESCE(pao2fio2_vent_min, pao2fio2_novent_min) IS NULL THEN NULL
            ELSE 0
        END AS respiration,
        CASE
            WHEN platelet_min < 20 THEN 4
            WHEN platelet_min < 50 THEN 3
            WHEN platelet_min < 100 THEN 2
            WHEN platelet_min < 150 THEN 1
            WHEN platelet_min IS NULL THEN NULL
            ELSE 0
        END AS coagulation,
        CASE
            WHEN bilirubin_max >= 12.0 THEN 4
            WHEN bilirubin_max >= 6.0 THEN 3
            WHEN bilirubin_max >= 2.0 THEN 2
            WHEN bilirubin_max >= 1.2 THEN 1
            WHEN bilirubin_max IS NULL THEN NULL
            ELSE 0
        END AS liver,
        CASE
            WHEN rate_dopamine > 15
                OR rate_epinephrine > CAST(0.1 AS FLOAT)
                OR rate_norepinephrine > CAST(0.1 AS FLOAT)
                THEN 4
            WHEN rate_dopamine > 5
                OR rate_epinephrine <= CAST(0.1 AS FLOAT)
                OR rate_norepinephrine <= CAST(0.1 AS FLOAT)
                THEN 3
            WHEN rate_dopamine > 0 OR rate_dobutamine > 0 THEN 2
            WHEN mbp_min < 70 THEN 1
            WHEN COALESCE(
                mbp_min,
                rate_dopamine,
                rate_dobutamine,
                rate_epinephrine,
                rate_norepinephrine
            ) IS NULL THEN NULL
            ELSE 0
        END AS cardiovascular,
        CASE
            WHEN gcs_min >= 13 AND gcs_min <= 14 THEN 1
            WHEN gcs_min >= 10 AND gcs_min <= 12 THEN 2
            WHEN gcs_min >= 6 AND gcs_min <= 9 THEN 3
            WHEN gcs_min < 6 THEN 4
            WHEN gcs_min IS NULL THEN NULL
            ELSE 0
        END AS cns,
        CASE
            WHEN creatinine_max >= 5.0 THEN 4
            WHEN urineoutput < 200 THEN 4
            WHEN creatinine_max >= 3.5 AND creatinine_max < 5.0 THEN 3
            WHEN urineoutput < 500 THEN 3
            WHEN creatinine_max >= 2.0 AND creatinine_max < 3.5 THEN 2
            WHEN creatinine_max >= 1.2 AND creatinine_max < 2.0 THEN 1
            WHEN COALESCE(urineoutput, creatinine_max) IS NULL THEN NULL
            ELSE 0
        END AS renal
    FROM scorecomp
)
SELECT
    CAST(
        COALESCE(s.respiration, 0)
        + COALESCE(s.coagulation, 0)
        + COALESCE(s.liver, 0)
        + COALESCE(s.cardiovascular, 0)
        + COALESCE(s.cns, 0)
        + COALESCE(s.renal, 0)
        AS INTEGER
    ) AS sofa,
    CAST(s.respiration AS INTEGER) AS respiration,
    CAST(s.coagulation AS INTEGER) AS coagulation,
    CAST(s.liver AS INTEGER) AS liver,
    CAST(s.cardiovascular AS INTEGER) AS cardiovascular,
    CAST(s.cns AS INTEGER) AS cns,
    CAST(s.renal AS INTEGER) AS renal,
    i.patient_key AS patient_key,
    i.encounter_key AS encounter_key,
    i.icu_encounter_key AS icu_encounter_key
FROM icu_stays AS i
LEFT JOIN scorecalc AS s
    ON i.icu_encounter_key = s.icu_encounter_key
;
