-- Readability copy -- not the artifact a server loads.
--
-- Library.phenylephrine.json in this directory is authoritative. This SQL is
-- the decoded form of its content.data, byte-identical to the sql-text
-- extension beside it. Edit neither: both are generated by
-- `mimic-utils metrics-finalize` from the finalized attempt.

WITH filtered_rows AS (
    SELECT
        ma.encounter_key,
        ma.patient_key,
        ma.effective_datetime,
        ma.effective_period_start,
        ma.effective_period_end,
        ma.rate_value,
        ma.rate_unit,
        ma.amount_value,
        ma.item_code,
        ma.code_system
    FROM medication_administration AS ma
    WHERE ma.code_system = 'http://mimic.mit.edu/fhir/mimic/CodeSystem/mimic-medication-icu'
      AND ma.item_code = '221749'
), typed_rows AS (
    SELECT
        e.stay_id_str,
        ma.patient_key,
        ma.encounter_key AS icu_encounter_key,
        ma.rate_unit,
        CAST(ma.rate_value AS DOUBLE) AS rate_value_double,
        CAST(ma.amount_value AS DOUBLE) AS amount_value_double,
        TRY_CAST(ma.effective_period_start AS TIMESTAMP_NTZ) AS effective_period_start_ntz,
        TRY_CAST(ma.effective_period_end AS TIMESTAMP_NTZ) AS effective_period_end_ntz,
        TRY_CAST(ma.effective_datetime AS TIMESTAMP_NTZ) AS effective_datetime_ntz
    FROM filtered_rows AS ma
    LEFT JOIN encounter_icu AS e
      ON ma.encounter_key = e.encounter_key
     AND e.stay_system = 'http://mimic.mit.edu/fhir/mimic/identifier/encounter-icu'
)
SELECT
    CAST(NULL AS INTEGER) AS linkorderid,
    CAST(
        CASE
            WHEN rate_unit = 'mcg/min' THEN CAST(NULL AS FLOAT)
            ELSE rate_value_double
        END AS FLOAT
    ) AS vaso_rate,
    CAST(amount_value_double AS FLOAT) AS vaso_amount,
    CAST(effective_period_start_ntz AS TIMESTAMP_NTZ) AS starttime,
    CAST(COALESCE(effective_period_end_ntz, effective_datetime_ntz) AS TIMESTAMP_NTZ) AS endtime,
    patient_key,
    icu_encounter_key
FROM typed_rows;
