-- Readability copy -- not the artifact a server loads.
--
-- Library.meld.json in this directory is authoritative. This SQL is
-- the decoded form of its content.data, byte-identical to the sql-text
-- extension beside it. Edit neither: both are generated by
-- `mimic-utils metrics-finalize` from the finalized attempt.

WITH cohort AS (
    SELECT
        p.subject_id_str AS subject_id,
        h.hadm_id_str AS hadm_id,
        e.stay_id_str AS stay_id,
        labs.creatinine_max,
        labs.bilirubin_total_max,
        labs.inr_max,
        labs.sodium_min,
        r.dialysis_present AS rrt,
        h.encounter_key,
        e.icu_encounter_key,
        p.patient_key
    FROM icu_encounter e
    LEFT JOIN patient p
        ON e.patient_key = p.patient_key
    LEFT JOIN hospital_encounter h
        ON e.encounter_key = h.encounter_key
    LEFT JOIN first_day_lab labs
        ON e.icu_encounter_key = labs.icu_encounter_key
    LEFT JOIN first_day_rrt r
        ON e.icu_encounter_key = r.icu_encounter_key
    WHERE e.stay_id_str IS NOT NULL
), score AS (
    SELECT
        subject_id,
        hadm_id,
        stay_id,
        rrt,
        creatinine_max,
        bilirubin_total_max,
        inr_max,
        sodium_min,
        encounter_key,
        icu_encounter_key,
        patient_key,

        CASE
            WHEN sodium_min IS NULL
                THEN 0.0
            WHEN sodium_min > 137
                THEN 0.0
            WHEN sodium_min < 125
                THEN 12.0
            ELSE 137.0 - sodium_min
        END AS sodium_score,

        CASE
            WHEN rrt = 1 OR creatinine_max > 4.0
                THEN 0.957 * LN(4)
            WHEN creatinine_max < 1
                THEN 0.957 * LN(1)
            ELSE 0.957 * COALESCE(LN(creatinine_max), LN(1))
        END AS creatinine_score,

        CASE
            WHEN bilirubin_total_max < 1
                THEN 0.378 * LN(1)
            ELSE 0.378 * COALESCE(LN(bilirubin_total_max), LN(1))
        END AS bilirubin_score,

        CASE
            WHEN inr_max < 1
                THEN 1.120 * LN(1) + 0.643
            ELSE 1.120 * COALESCE(LN(inr_max), LN(1)) + 0.643
        END AS inr_score
    FROM cohort
), score2 AS (
    SELECT
        subject_id,
        hadm_id,
        stay_id,
        rrt,
        creatinine_max,
        bilirubin_total_max,
        inr_max,
        sodium_min,
        sodium_score,
        creatinine_score,
        bilirubin_score,
        inr_score,
        encounter_key,
        icu_encounter_key,
        patient_key,

        CASE
            WHEN (creatinine_score + bilirubin_score + inr_score) > 4
                THEN 40.0
            ELSE ROUND(
                CAST(
                    creatinine_score
                    + bilirubin_score
                    + inr_score
                    AS DECIMAL(38,12)
                ),
                1
            ) * 10
        END AS meld_initial
    FROM score
), final_values AS (
    SELECT
        subject_id,
        hadm_id,
        stay_id,
        meld_initial,
        CASE
            WHEN meld_initial > 11
                THEN meld_initial + 1.32 * sodium_score
                    - 0.033 * meld_initial * sodium_score
            ELSE meld_initial
        END AS meld,
        rrt,
        creatinine_max,
        bilirubin_total_max,
        inr_max,
        sodium_min,
        encounter_key,
        icu_encounter_key,
        patient_key
    FROM score2
)
SELECT
    CAST(f.meld_initial AS DECIMAL(38,1)) AS meld_initial,
    CAST(f.meld AS DOUBLE) AS meld,
    CAST(f.rrt AS INTEGER) AS rrt,
    CAST(f.creatinine_max AS DOUBLE) AS creatinine_max,
    CAST(f.bilirubin_total_max AS DOUBLE) AS bilirubin_total_max,
    CAST(f.inr_max AS DOUBLE) AS inr_max,
    CAST(f.sodium_min AS DOUBLE) AS sodium_min,
    f.encounter_key AS encounter_key,
    f.icu_encounter_key AS icu_encounter_key,
    f.patient_key AS patient_key
FROM final_values f
;
