-- Readability copy -- not the artifact a server loads.
--
-- Library.height.json in this directory is authoritative. This SQL is
-- the decoded form of its content.data, byte-identical to the sql-text
-- extension beside it. Edit neither: both are generated by
-- `mimic-utils metrics-finalize` from the finalized attempt.

WITH observation_rows AS (
    SELECT
        p.patient_key,
        e.encounter_key AS icu_encounter_key,
        p.subject_id_str,
        e.stay_id_str,
        o.item_code,
        o.item_system,
        TRY_CAST(o.effective_datetime AS TIMESTAMP_NTZ) AS charttime,
        CAST(o.quantity_value AS DOUBLE) AS value_num
    FROM height_observation o
    INNER JOIN height_patient p
        ON o.patient_key = p.patient_key
    INNER JOIN height_encounter e
        ON o.encounter_key = e.encounter_key
        AND o.patient_key = e.patient_key
    WHERE o.item_system = 'http://mimic.mit.edu/fhir/mimic/CodeSystem/mimic-chartevents-d-items'
        AND o.item_code IN ('226707', '226730')
        AND o.quantity_value IS NOT NULL
        AND p.subject_id_str IS NOT NULL
        AND e.stay_id_str IS NOT NULL
), ht_in AS (
    SELECT
        patient_key,
        icu_encounter_key,
        subject_id_str,
        stay_id_str,
        charttime,
        ROUND(value_num * 2.54, 2) AS height
    FROM observation_rows
    WHERE item_code = '226707'
), ht_cm AS (
    SELECT
        patient_key,
        icu_encounter_key,
        subject_id_str,
        stay_id_str,
        charttime,
        ROUND(value_num, 2) AS height
    FROM observation_rows
    WHERE item_code = '226730'
), ht_stg0 AS (
    SELECT
        COALESCE(h1.patient_key, h2.patient_key) AS patient_key,
        COALESCE(h1.icu_encounter_key, h2.icu_encounter_key) AS icu_encounter_key,
        COALESCE(h1.subject_id_str, h2.subject_id_str) AS subject_id_str,
        COALESCE(h1.stay_id_str, h2.stay_id_str) AS stay_id_str,
        COALESCE(h1.charttime, h2.charttime) AS charttime,
        COALESCE(h1.height, h2.height) AS height
    FROM ht_cm h1
    FULL OUTER JOIN ht_in h2
        ON h1.subject_id_str = h2.subject_id_str
        AND h1.charttime = h2.charttime
)
SELECT
    CAST(charttime AS TIMESTAMP) AS charttime,
    CAST(height AS DECIMAL(38,2)) AS height,
    patient_key,
    icu_encounter_key
FROM ht_stg0
WHERE height IS NOT NULL
    AND height > 120
    AND height < 230
;
