-- Readability copy -- not the artifact a server loads.
--
-- Library.oxygen_delivery.json in this directory is authoritative. This SQL is
-- the decoded form of its content.data, byte-identical to the sql-text
-- extension beside it. Edit neither: both are generated by
-- `mimic-utils metrics-finalize` from the finalized attempt.

WITH observation_rows AS (
    SELECT
        o.patient_key,
        o.encounter_key,
        o.code,
        o.system,
        COALESCE(
            TRY_CAST(o.effective_datetime AS TIMESTAMP_NTZ),
            TRY_CAST(o.effective_period_start AS TIMESTAMP_NTZ)
        ) AS charttime,
        CAST(o.quantity_value AS DOUBLE) AS valuenum,
        o.string_value AS value,
        o.issued
    FROM oxygen_delivery_observation o
    WHERE o.system = 'http://mimic.mit.edu/fhir/mimic/CodeSystem/mimic-chartevents-d-items'
        AND o.code IN ('223834', '227582', '227287', '226732')
), identified_rows AS (
    SELECT
        o.patient_key,
        e.icu_encounter_key,
        p.subject_id_str,
        e.stay_id_str,
        o.code,
        o.charttime,
        o.valuenum,
        o.value,
        o.issued
    FROM observation_rows o
    INNER JOIN oxygen_delivery_patient p
        ON o.patient_key = p.patient_key
    INNER JOIN oxygen_delivery_encounter e
        ON o.encounter_key = e.icu_encounter_key
), flow_stg1 AS (
    SELECT
        patient_key,
        icu_encounter_key,
        subject_id_str,
        CAST(stay_id_str AS INTEGER) AS stay_id,
        charttime,
        CASE
            WHEN code IN ('223834', '227582') THEN '223834'
            ELSE code
        END AS item_code,
        value,
        valuenum,
        issued
    FROM identified_rows
    WHERE code IN ('223834', '227582', '227287')
        AND (valuenum IS NOT NULL OR value IS NOT NULL)
), flow_stg2 AS (
    SELECT
        f.*,
        ROW_NUMBER() OVER (
            PARTITION BY patient_key, charttime, item_code
            ORDER BY issued DESC, valuenum DESC
        ) AS rn
    FROM flow_stg1 f
), flow_selected AS (
    SELECT
        patient_key,
        icu_encounter_key,
        subject_id_str,
        stay_id,
        charttime,
        item_code,
        valuenum
    FROM flow_stg2
    WHERE rn = 1
), device_ranked AS (
    SELECT
        patient_key,
        charttime,
        value AS o2_device,
        ROW_NUMBER() OVER (
            PARTITION BY patient_key, charttime, code
            ORDER BY issued DESC NULLS LAST, value DESC NULLS LAST
        ) AS rn
    FROM identified_rows
    WHERE code = '226732'
), stg AS (
    SELECT
        f.patient_key,
        f.subject_id_str,
        f.stay_id,
        f.charttime,
        f.item_code,
        f.valuenum,
        d.o2_device,
        d.rn
    FROM flow_selected f
    LEFT JOIN device_ranked d
        ON f.patient_key = d.patient_key
        AND f.charttime = d.charttime
), aggregated AS (
    SELECT
        patient_key,
        subject_id_str,
        charttime,
        MAX(stay_id) AS stay_id,
        MAX(CASE WHEN item_code = '223834' THEN valuenum ELSE NULL END) AS o2_flow,
        MAX(CASE WHEN item_code = '227287' THEN valuenum ELSE NULL END) AS o2_flow_additional,
        MAX(CASE WHEN rn = 1 THEN o2_device ELSE NULL END) AS o2_delivery_device_1,
        MAX(CASE WHEN rn = 2 THEN o2_device ELSE NULL END) AS o2_delivery_device_2,
        MAX(CASE WHEN rn = 3 THEN o2_device ELSE NULL END) AS o2_delivery_device_3,
        MAX(CASE WHEN rn = 4 THEN o2_device ELSE NULL END) AS o2_delivery_device_4
    FROM stg
    GROUP BY patient_key, subject_id_str, charttime
), flow_max_stay AS (
    SELECT
        patient_key,
        subject_id_str,
        charttime,
        MAX(stay_id) AS stay_id
    FROM flow_selected
    GROUP BY patient_key, subject_id_str, charttime
), stay_keys AS (
    SELECT
        f.patient_key,
        f.subject_id_str,
        f.charttime,
        f.icu_encounter_key
    FROM flow_selected f
    INNER JOIN flow_max_stay m
        ON f.patient_key = m.patient_key
        AND f.subject_id_str = m.subject_id_str
        AND f.charttime = m.charttime
        AND f.stay_id = m.stay_id
    GROUP BY f.patient_key, f.subject_id_str, f.charttime, f.icu_encounter_key
)
SELECT
    CAST(a.charttime AS TIMESTAMP_NTZ) AS charttime,
    CAST(a.o2_flow AS FLOAT) AS o2_flow,
    CAST(a.o2_flow_additional AS FLOAT) AS o2_flow_additional,
    CAST(a.o2_delivery_device_1 AS VARCHAR(255)) AS o2_delivery_device_1,
    CAST(a.o2_delivery_device_2 AS VARCHAR(255)) AS o2_delivery_device_2,
    CAST(a.o2_delivery_device_3 AS VARCHAR(255)) AS o2_delivery_device_3,
    CAST(a.o2_delivery_device_4 AS VARCHAR(255)) AS o2_delivery_device_4,
    a.patient_key,
    k.icu_encounter_key
FROM aggregated a
INNER JOIN stay_keys k
    ON a.patient_key = k.patient_key
    AND a.subject_id_str = k.subject_id_str
    AND a.charttime = k.charttime
;
