-- Readability copy -- not the artifact a server loads.
--
-- Library.enzyme.json in this directory is authoritative. This SQL is
-- the decoded form of its content.data, byte-identical to the sql-text
-- extension beside it. Edit neither: both are generated by
-- `mimic-utils metrics-finalize` from the finalized attempt.

WITH filtered_rows AS (
    SELECT
        p.subject_id_str,
        p.patient_key,
        e.hadm_id_str,
        e.encounter_key,
        s.specimen_id_str,
        s.specimen_key,
        l.code,
        l.system,
        l.effective_datetime,
        l.effective_period_start,
        l.quantity_value,
        l.quantity_comparator,
        l.value_string
    FROM lab_observation AS l
    INNER JOIN patient AS p
        ON l.patient_key = p.patient_key
    INNER JOIN specimen AS s
        ON l.specimen_key = s.specimen_key
    LEFT JOIN encounter AS e
        ON l.encounter_key = e.encounter_key
    WHERE l.system = 'http://mimic.mit.edu/fhir/mimic/CodeSystem/mimic-d-labitems'
        AND l.code IN (
            '50861', '50863', '50878', '50867', '50885', '50883',
            '50884', '50910', '50911', '50927', '50954'
        )
        AND l.quantity_value IS NOT NULL
        AND l.quantity_comparator IS NULL
        AND l.value_string IS NULL
), typed_rows AS (
    SELECT
        CAST(subject_id_str AS INTEGER) AS subject_id,
        patient_key,
        CAST(hadm_id_str AS INTEGER) AS hadm_id,
        encounter_key,
        CAST(specimen_id_str AS INTEGER) AS specimen_id,
        specimen_key,
        code,
        COALESCE(
            TRY_CAST(effective_datetime AS TIMESTAMP_NTZ),
            TRY_CAST(effective_period_start AS TIMESTAMP_NTZ)
        ) AS charttime,
        CAST(quantity_value AS DOUBLE) AS value_num
    FROM filtered_rows
), eligible_rows AS (
    SELECT
        subject_id,
        patient_key,
        hadm_id,
        encounter_key,
        specimen_id,
        specimen_key,
        code,
        charttime,
        value_num
    FROM typed_rows
    WHERE value_num IS NOT NULL
        AND value_num > 0
), grouped AS (
    SELECT
        MAX(subject_id) AS subject_id,
        MAX(patient_key) AS patient_key,
        MAX(hadm_id) AS hadm_id,
        MAX(encounter_key) AS encounter_key,
        MAX(charttime) AS charttime,
        specimen_id,
        MAX(specimen_key) AS specimen_key,
        MAX(CASE WHEN code = '50861' THEN value_num ELSE NULL END) AS alt,
        MAX(CASE WHEN code = '50863' THEN value_num ELSE NULL END) AS alp,
        MAX(CASE WHEN code = '50878' THEN value_num ELSE NULL END) AS ast,
        MAX(CASE WHEN code = '50867' THEN value_num ELSE NULL END) AS amylase,
        MAX(CASE WHEN code = '50885' THEN value_num ELSE NULL END) AS bilirubin_total,
        MAX(CASE WHEN code = '50883' THEN value_num ELSE NULL END) AS bilirubin_direct,
        MAX(CASE WHEN code = '50884' THEN value_num ELSE NULL END) AS bilirubin_indirect,
        MAX(CASE WHEN code = '50910' THEN value_num ELSE NULL END) AS ck_cpk,
        MAX(CASE WHEN code = '50911' THEN value_num ELSE NULL END) AS ck_mb,
        MAX(CASE WHEN code = '50927' THEN value_num ELSE NULL END) AS ggt,
        MAX(CASE WHEN code = '50954' THEN value_num ELSE NULL END) AS ld_ldh
    FROM eligible_rows
    GROUP BY specimen_id
)
SELECT
    grouped.patient_key AS patient_key,
    grouped.encounter_key AS encounter_key,
    CAST(grouped.charttime AS TIMESTAMP) AS charttime,
    grouped.specimen_key AS specimen_key,
    CAST(grouped.alt AS DOUBLE) AS alt,
    CAST(grouped.alp AS DOUBLE) AS alp,
    CAST(grouped.ast AS DOUBLE) AS ast,
    CAST(grouped.amylase AS DOUBLE) AS amylase,
    CAST(grouped.bilirubin_total AS DOUBLE) AS bilirubin_total,
    CAST(grouped.bilirubin_direct AS DOUBLE) AS bilirubin_direct,
    CAST(grouped.bilirubin_indirect AS DOUBLE) AS bilirubin_indirect,
    CAST(grouped.ck_cpk AS DOUBLE) AS ck_cpk,
    CAST(grouped.ck_mb AS DOUBLE) AS ck_mb,
    CAST(grouped.ggt AS DOUBLE) AS ggt,
    CAST(grouped.ld_ldh AS DOUBLE) AS ld_ldh
FROM grouped
;
