-- Readability copy -- not the artifact a server loads.
--
-- Library.first_day_vitalsign.json in this directory is authoritative. This SQL is
-- the decoded form of its content.data, byte-identical to the sql-text
-- extension beside it. Edit neither: both are generated by
-- `mimic-utils metrics-finalize` from the finalized attempt.

WITH icu AS (
    SELECT
        p.subject_id_str,
        e.stay_id_str,
        TRY_CAST(e.intime_datetime AS TIMESTAMP_NTZ) AS intime,
        e.patient_key,
        e.icu_encounter_key
    FROM icu_encounter e
    LEFT JOIN patient p
        ON e.patient_key = p.patient_key
    WHERE e.stay_system = 'http://mimic.mit.edu/fhir/mimic/identifier/encounter-icu'
        AND e.stay_id_str IS NOT NULL
), aggregated AS (
    SELECT
        i.subject_id_str,
        i.stay_id_str,
        i.patient_key,
        i.icu_encounter_key,
        MIN(v.heart_rate) AS heart_rate_min,
        MAX(v.heart_rate) AS heart_rate_max,
        AVG(v.heart_rate) AS heart_rate_mean,
        MIN(v.sbp) AS sbp_min,
        MAX(v.sbp) AS sbp_max,
        AVG(v.sbp) AS sbp_mean,
        MIN(v.dbp) AS dbp_min,
        MAX(v.dbp) AS dbp_max,
        AVG(v.dbp) AS dbp_mean,
        MIN(v.mbp) AS mbp_min,
        MAX(v.mbp) AS mbp_max,
        AVG(v.mbp) AS mbp_mean,
        MIN(v.resp_rate) AS resp_rate_min,
        MAX(v.resp_rate) AS resp_rate_max,
        AVG(v.resp_rate) AS resp_rate_mean,
        MIN(v.temperature) AS temperature_min,
        MAX(v.temperature) AS temperature_max,
        AVG(v.temperature) AS temperature_mean,
        MIN(v.spo2) AS spo2_min,
        MAX(v.spo2) AS spo2_max,
        AVG(v.spo2) AS spo2_mean,
        MIN(v.glucose) AS glucose_min,
        MAX(v.glucose) AS glucose_max,
        AVG(v.glucose) AS glucose_mean
    FROM icu i
    LEFT JOIN vitalsign v
        ON i.icu_encounter_key = v.icu_encounter_key
        AND v.charttime >= i.intime - INTERVAL 6 HOURS
        AND v.charttime <= i.intime + INTERVAL 1 DAY
    GROUP BY
        i.subject_id_str,
        i.stay_id_str,
        i.patient_key,
        i.icu_encounter_key
)
SELECT
    CAST(a.heart_rate_min AS DOUBLE) AS heart_rate_min,
    CAST(a.heart_rate_max AS DOUBLE) AS heart_rate_max,
    CAST(a.heart_rate_mean AS DOUBLE) AS heart_rate_mean,
    CAST(a.sbp_min AS DOUBLE) AS sbp_min,
    CAST(a.sbp_max AS DOUBLE) AS sbp_max,
    CAST(a.sbp_mean AS DOUBLE) AS sbp_mean,
    CAST(a.dbp_min AS DOUBLE) AS dbp_min,
    CAST(a.dbp_max AS DOUBLE) AS dbp_max,
    CAST(a.dbp_mean AS DOUBLE) AS dbp_mean,
    CAST(a.mbp_min AS DOUBLE) AS mbp_min,
    CAST(a.mbp_max AS DOUBLE) AS mbp_max,
    CAST(a.mbp_mean AS DOUBLE) AS mbp_mean,
    CAST(a.resp_rate_min AS DOUBLE) AS resp_rate_min,
    CAST(a.resp_rate_max AS DOUBLE) AS resp_rate_max,
    CAST(a.resp_rate_mean AS DOUBLE) AS resp_rate_mean,
    CAST(a.temperature_min AS DECIMAL(38, 2)) AS temperature_min,
    CAST(a.temperature_max AS DECIMAL(38, 2)) AS temperature_max,
    CAST(a.temperature_mean AS DOUBLE) AS temperature_mean,
    CAST(a.spo2_min AS DOUBLE) AS spo2_min,
    CAST(a.spo2_max AS DOUBLE) AS spo2_max,
    CAST(a.spo2_mean AS DOUBLE) AS spo2_mean,
    CAST(a.glucose_min AS DOUBLE) AS glucose_min,
    CAST(a.glucose_max AS DOUBLE) AS glucose_max,
    CAST(a.glucose_mean AS DOUBLE) AS glucose_mean,
    a.icu_encounter_key AS icu_encounter_key,
    a.patient_key AS patient_key
FROM aggregated a
;
