-- Readability copy -- not the artifact a server loads.
--
-- Library.lods.json in this directory is authoritative. This SQL is
-- the decoded form of its content.data, byte-identical to the sql-text
-- extension beside it. Edit neither: both are generated by
-- `mimic-utils metrics-finalize` from the finalized attempt.

WITH icu AS (
    SELECT
        i.icu_encounter_key,
        i.patient_key,
        i.encounter_key,
        i.stay_id_str,
        TRY_CAST(i.intime_datetime AS TIMESTAMP_NTZ) AS intime,
        TRY_CAST(i.outtime_datetime AS TIMESTAMP_NTZ) AS outtime
    FROM icu_encounter AS i
    WHERE i.stay_system = 'http://mimic.mit.edu/fhir/mimic/identifier/encounter-icu'
        AND i.stay_id_str IS NOT NULL
), cpap AS (
    SELECT
        i.icu_encounter_key,
        MIN(
            TRY_CAST(
                COALESCE(c.effective_datetime, c.effective_period_start)
                AS TIMESTAMP_NTZ
            ) - INTERVAL 1 HOUR
        ) AS starttime,
        MAX(
            TRY_CAST(
                COALESCE(c.effective_datetime, c.effective_period_start)
                AS TIMESTAMP_NTZ
            ) + INTERVAL 4 HOURS
        ) AS endtime,
        MAX(
            CASE
                WHEN LOWER(c.value_string) LIKE '%cpap%' THEN 1
                WHEN LOWER(c.value_string) LIKE '%bipap mask%' THEN 1
                ELSE 0
            END
        ) AS cpap
    FROM icu AS i
    INNER JOIN cpap_observation AS c
        ON i.icu_encounter_key = c.icu_encounter_key
    WHERE c.system = 'http://mimic.mit.edu/fhir/mimic/CodeSystem/mimic-chartevents-d-items'
        AND c.code = '226732'
        AND TRY_CAST(
                COALESCE(c.effective_datetime, c.effective_period_start)
                AS TIMESTAMP_NTZ
            ) >= i.intime
        AND TRY_CAST(
                COALESCE(c.effective_datetime, c.effective_period_start)
                AS TIMESTAMP_NTZ
            ) <= i.intime + INTERVAL 1 DAY
        AND (
            LOWER(c.value_string) LIKE '%cpap%'
            OR LOWER(c.value_string) LIKE '%bipap mask%'
        )
    GROUP BY i.icu_encounter_key
), pafi1 AS (
    SELECT
        i.icu_encounter_key,
        b.charttime,
        b.pao2fio2ratio,
        CASE WHEN v.icu_encounter_key IS NOT NULL THEN 1 ELSE 0 END AS vent,
        CASE WHEN c.icu_encounter_key IS NOT NULL THEN 1 ELSE 0 END AS cpap
    FROM bg AS b
    INNER JOIN icu AS i
        ON b.encounter_key = i.encounter_key
        AND b.charttime >= i.intime
        AND b.charttime < i.outtime
    LEFT JOIN ventilation AS v
        ON i.icu_encounter_key = v.icu_encounter_key
        AND b.charttime >= v.starttime
        AND b.charttime <= v.endtime
        AND v.ventilation_status = 'InvasiveVent'
    LEFT JOIN cpap AS c
        ON i.icu_encounter_key = c.icu_encounter_key
        AND b.charttime >= c.starttime
        AND b.charttime <= c.endtime
), pafi2 AS (
    SELECT
        p.icu_encounter_key,
        MIN(p.pao2fio2ratio) AS pao2fio2_vent_min
    FROM pafi1 AS p
    WHERE p.vent = 1 OR p.cpap = 1
    GROUP BY p.icu_encounter_key
), cohort AS (
    SELECT
        i.icu_encounter_key,
        i.patient_key,
        i.encounter_key,
        p.subject_id_str,
        h.hadm_id_str,
        i.stay_id_str,
        i.intime,
        i.outtime,
        g.gcs_min,
        vital.heart_rate_max,
        vital.heart_rate_min,
        vital.sbp_max,
        vital.sbp_min,
        pf.pao2fio2_vent_min,
        labs.bun_max,
        labs.bun_min,
        labs.wbc_max,
        labs.wbc_min,
        labs.bilirubin_total_max AS bilirubin_max,
        labs.creatinine_max,
        labs.pt_min,
        labs.pt_max,
        labs.platelets_min AS platelet_min,
        uo.urineoutput
    FROM icu AS i
    INNER JOIN hospital_encounter AS h
        ON i.encounter_key = h.encounter_key
        AND h.hadm_id_str IS NOT NULL
    INNER JOIN patient AS p
        ON i.patient_key = p.patient_key
        AND p.subject_id_str IS NOT NULL
    LEFT JOIN pafi2 AS pf
        ON i.icu_encounter_key = pf.icu_encounter_key
    LEFT JOIN first_day_gcs AS g
        ON i.icu_encounter_key = g.icu_encounter_key
    LEFT JOIN first_day_vitalsign AS vital
        ON i.icu_encounter_key = vital.icu_encounter_key
    LEFT JOIN first_day_urine_output AS uo
        ON i.icu_encounter_key = uo.icu_encounter_key
    LEFT JOIN first_day_lab AS labs
        ON i.icu_encounter_key = labs.icu_encounter_key
), scorecomp AS (
    SELECT
        c.*,
        CASE
            WHEN c.gcs_min IS NULL THEN NULL
            WHEN c.gcs_min < 3 THEN NULL
            WHEN c.gcs_min <= 5 THEN 5
            WHEN c.gcs_min <= 8 THEN 3
            WHEN c.gcs_min <= 13 THEN 1
            ELSE 0
        END AS neurologic,
        CASE
            WHEN c.heart_rate_max IS NULL
                AND c.sbp_min IS NULL THEN NULL
            WHEN c.heart_rate_min < 30 THEN 5
            WHEN c.sbp_min < 40 THEN 5
            WHEN c.sbp_min < 70 THEN 3
            WHEN c.sbp_max >= 270 THEN 3
            WHEN c.heart_rate_max >= 140 THEN 1
            WHEN c.sbp_max >= 240 THEN 1
            WHEN c.sbp_min < 90 THEN 1
            ELSE 0
        END AS cardiovascular,
        CASE
            WHEN c.bun_max IS NULL
                OR c.urineoutput IS NULL
                OR c.creatinine_max IS NULL THEN NULL
            WHEN c.urineoutput < 500.0 THEN 5
            WHEN c.bun_max >= 56.0 THEN 5
            WHEN c.creatinine_max >= 1.60 THEN 3
            WHEN c.urineoutput < 750.0 THEN 3
            WHEN c.bun_max >= 28.0 THEN 3
            WHEN c.urineoutput >= 10000.0 THEN 3
            WHEN c.creatinine_max >= 1.20 THEN 1
            WHEN c.bun_max >= 17.0 THEN 1
            WHEN c.bun_max >= 7.50 THEN 1
            ELSE 0
        END AS renal,
        CASE
            WHEN c.pao2fio2_vent_min IS NULL THEN 0
            WHEN c.pao2fio2_vent_min >= 150 THEN 1
            WHEN c.pao2fio2_vent_min < 150 THEN 3
            ELSE NULL
        END AS pulmonary,
        CASE
            WHEN c.wbc_max IS NULL
                AND c.platelet_min IS NULL THEN NULL
            WHEN c.wbc_min < 1.0 THEN 3
            WHEN c.wbc_min < 2.5 THEN 1
            WHEN c.platelet_min < 50.0 THEN 1
            WHEN c.wbc_max >= 50.0 THEN 1
            ELSE 0
        END AS hematologic,
        CASE
            WHEN c.pt_max IS NULL
                AND c.bilirubin_max IS NULL THEN NULL
            WHEN c.bilirubin_max >= 2.0 THEN 1
            WHEN c.pt_max > (12 + 3) THEN 1
            WHEN c.pt_min < (12 * 0.25) THEN 1
            ELSE 0
        END AS hepatic
    FROM cohort AS c
), final_rows AS (
    SELECT
        p.subject_id_str,
        h.hadm_id_str,
        i.stay_id_str,
        COALESCE(s.neurologic, 0)
            + COALESCE(s.cardiovascular, 0)
            + COALESCE(s.renal, 0)
            + COALESCE(s.pulmonary, 0)
            + COALESCE(s.hematologic, 0)
            + COALESCE(s.hepatic, 0) AS lods,
        s.neurologic,
        s.cardiovascular,
        s.renal,
        s.pulmonary,
        s.hematologic,
        s.hepatic,
        h.encounter_key,
        i.icu_encounter_key,
        p.patient_key
    FROM icu AS i
    LEFT JOIN hospital_encounter AS h
        ON i.encounter_key = h.encounter_key
    LEFT JOIN patient AS p
        ON i.patient_key = p.patient_key
    LEFT JOIN scorecomp AS s
        ON i.icu_encounter_key = s.icu_encounter_key
    WHERE i.stay_id_str IS NOT NULL
)
SELECT
    CAST(f.lods AS INTEGER) AS lods,
    CAST(f.neurologic AS INTEGER) AS neurologic,
    CAST(f.cardiovascular AS INTEGER) AS cardiovascular,
    CAST(f.renal AS INTEGER) AS renal,
    CAST(f.pulmonary AS INTEGER) AS pulmonary,
    CAST(f.hematologic AS INTEGER) AS hematologic,
    CAST(f.hepatic AS INTEGER) AS hepatic,
    f.encounter_key,
    f.icu_encounter_key,
    f.patient_key
FROM final_rows AS f
;
