-- Readability copy -- not the artifact a server loads.
--
-- Library.icp.json in this directory is authoritative. This SQL is
-- the decoded form of its content.data, byte-identical to the sql-text
-- extension beside it. Edit neither: both are generated by
-- `mimic-utils metrics-finalize` from the finalized attempt.

WITH filtered_rows AS (
    SELECT
        p.subject_id_str,
        e.stay_id_str,
        o.patient_key,
        o.icu_encounter_key,
        TRY_CAST(o.effective_datetime AS TIMESTAMP_NTZ) AS charttime,
        CAST(o.quantity_value AS DOUBLE) AS quantity_num
    FROM icp_observation o
    INNER JOIN icp_patient p
        ON o.patient_key = p.patient_key
    INNER JOIN icp_icu_encounter e
        ON o.icu_encounter_key = e.icu_encounter_key
        AND o.patient_key = e.patient_key
    WHERE o.code_system = 'http://mimic.mit.edu/fhir/mimic/CodeSystem/mimic-chartevents-d-items'
        AND o.item_code IN ('220765', '227989')
        AND p.subject_id_str IS NOT NULL
        AND e.stay_id_str IS NOT NULL
), grouped AS (
    SELECT
        subject_id_str,
        stay_id_str,
        charttime,
        MAX(patient_key) AS patient_key,
        MAX(icu_encounter_key) AS icu_encounter_key,
        MAX(
            CASE
                WHEN quantity_num > 0 AND quantity_num < 100 THEN quantity_num
                ELSE NULL
            END
        ) AS icp
    FROM filtered_rows
    GROUP BY subject_id_str, stay_id_str, charttime
)
SELECT
    patient_key AS patient_key,
    icu_encounter_key AS icu_encounter_key,
    CAST(charttime AS TIMESTAMP_NTZ) AS charttime,
    CAST(icp AS FLOAT) AS icp
FROM grouped
;
