-- Readability copy -- not the artifact a server loads.
--
-- Library.kdigo_creatinine.json in this directory is authoritative. This SQL is
-- the decoded form of its content.data, byte-identical to the sql-text
-- extension beside it. Edit neither: both are generated by
-- `mimic-utils metrics-finalize` from the finalized attempt.

WITH icu_encounters AS (
    SELECT
        i.encounter_key,
        i.patient_key,
        i.parent_encounter_key,
        i.stay_id_str,
        TRY_CAST(i.period_start AS TIMESTAMP_NTZ) AS intime,
        TRY_CAST(i.period_end AS TIMESTAMP_NTZ) AS outtime
    FROM icu_encounter i
    WHERE i.stay_id_str IS NOT NULL
), hospital_encounters AS (
    SELECT
        h.encounter_key,
        h.hadm_id_str
    FROM hospital_encounter h
    WHERE h.hadm_id_str IS NOT NULL
), icu_with_admission AS (
    SELECT
        i.patient_key,
        i.stay_id_str,
        i.intime,
        i.outtime,
        h.hadm_id_str
    FROM icu_encounters i
    LEFT JOIN hospital_encounters h
        ON i.parent_encounter_key = h.encounter_key
), observations AS (
    SELECT
        o.patient_key,
        TRY_CAST(o.effective_datetime AS TIMESTAMP_NTZ) AS charttime,
        CAST(o.quantity_value AS DOUBLE) AS creat_value
    FROM lab_observation o
    WHERE o.system = 'http://mimic.mit.edu/fhir/mimic/CodeSystem/mimic-d-labitems'
        AND o.code = '50912'
        AND o.quantity_value IS NOT NULL
        AND o.quantity_comparator IS NULL
        AND o.value_string IS NULL
), cr AS (
    SELECT
        i.hadm_id_str,
        i.stay_id_str,
        o.charttime,
        AVG(o.creat_value) AS creat
    FROM icu_with_admission i
    LEFT JOIN observations o
        ON i.patient_key = o.patient_key
        AND o.creat_value <= 150
        AND o.charttime >= i.intime - INTERVAL 7 DAYS
        AND o.charttime <= i.outtime
    GROUP BY i.hadm_id_str, i.stay_id_str, o.charttime
), cr48 AS (
    SELECT
        c.stay_id_str,
        c.charttime,
        MIN(prior.creat) AS creat_low_past_48hr
    FROM cr c
    LEFT JOIN cr prior
        ON c.stay_id_str = prior.stay_id_str
        AND prior.charttime < c.charttime
        AND prior.charttime >= c.charttime - INTERVAL 48 HOURS
    GROUP BY c.stay_id_str, c.charttime
), cr7 AS (
    SELECT
        c.stay_id_str,
        c.charttime,
        MIN(prior.creat) AS creat_low_past_7day
    FROM cr c
    LEFT JOIN cr prior
        ON c.stay_id_str = prior.stay_id_str
        AND prior.charttime < c.charttime
        AND prior.charttime >= c.charttime - INTERVAL 7 DAYS
    GROUP BY c.stay_id_str, c.charttime
)
SELECT
    CAST(cr.charttime AS TIMESTAMP_NTZ) AS charttime,
    CAST(cr.creat AS DOUBLE) AS creat,
    CAST(cr48.creat_low_past_48hr AS DOUBLE) AS creat_low_past_48hr,
    CAST(cr7.creat_low_past_7day AS DOUBLE) AS creat_low_past_7day,
    (
        SELECT MAX(i.patient_key)
        FROM icu_encounters i
        WHERE i.stay_id_str = cr.stay_id_str
    ) AS patient_key,
    (
        SELECT MAX(h.encounter_key)
        FROM icu_encounters i
        LEFT JOIN hospital_encounters h
            ON i.parent_encounter_key = h.encounter_key
        WHERE i.stay_id_str = cr.stay_id_str
    ) AS encounter_key,
    (
        SELECT MAX(i.encounter_key)
        FROM icu_encounters i
        WHERE i.stay_id_str = cr.stay_id_str
    ) AS icu_encounter_key
FROM cr
LEFT JOIN cr48
    ON cr.stay_id_str = cr48.stay_id_str
    AND cr.charttime = cr48.charttime
LEFT JOIN cr7
    ON cr.stay_id_str = cr7.stay_id_str
    AND cr.charttime = cr7.charttime
;
