-- Readability copy -- not the artifact a server loads.
--
-- Library.first_day_height.json in this directory is authoritative. This SQL is
-- the decoded form of its content.data, byte-identical to the sql-text
-- extension beside it. Edit neither: both are generated by
-- `mimic-utils metrics-finalize` from the finalized attempt.

WITH icu AS (
    SELECT
        CAST(p.subject_id_str AS INTEGER) AS subject_id,
        CAST(e.stay_id_str AS INTEGER) AS stay_id,
        TRY_CAST(e.period_start AS TIMESTAMP_NTZ) AS period_start,
        e.patient_key AS patient_key,
        e.icu_encounter_key AS icu_encounter_key
    FROM icu_encounter e
    LEFT JOIN patient p
        ON e.patient_key = p.patient_key
    WHERE e.stay_id_str IS NOT NULL
), aggregated AS (
    SELECT
        i.subject_id,
        i.stay_id,
        i.patient_key,
        i.icu_encounter_key,
        ROUND(AVG(h.height), 2) AS height
    FROM icu i
    LEFT JOIN height h
        ON i.icu_encounter_key = h.icu_encounter_key
        AND h.charttime >= i.period_start - INTERVAL 6 HOURS
        AND h.charttime <= i.period_start + INTERVAL 1 DAY
    GROUP BY
        i.subject_id,
        i.stay_id,
        i.patient_key,
        i.icu_encounter_key
)
SELECT
    CAST(a.height AS DECIMAL(38,2)) AS height,
    a.patient_key,
    a.icu_encounter_key
FROM aggregated a
;
