-- Readability copy -- not the artifact a server loads.
--
-- Library.age.json in this directory is authoritative. This SQL is
-- the decoded form of its content.data, byte-identical to the sql-text
-- extension beside it. Edit neither: both are generated by
-- `mimic-utils metrics-finalize` from the finalized attempt.

SELECT
    TRY_CAST(e.period_start AS TIMESTAMP_NTZ) AS admittime,
    CAST(NULL AS SMALLINT) AS anchor_age,
    CAST(NULL AS SMALLINT) AS anchor_year,
    CAST(
        YEAR(TRY_CAST(e.period_start AS TIMESTAMP_NTZ))
        - YEAR(TRY_CAST(p.birth_date AS DATE))
        AS BIGINT
    ) AS age,
    p.patient_key,
    e.encounter_key
FROM encounter e
INNER JOIN patient p
    ON e.patient_key = p.patient_key
WHERE e.hadm_id_str IS NOT NULL
;
