WITH icu AS (
    SELECT
        CAST(p.subject_id_str AS INTEGER) AS subject_id,
        CAST(e.stay_id_str AS INTEGER) AS stay_id,
        TRY_CAST(e.intime_datetime AS TIMESTAMP_NTZ) AS intime,
        p.patient_key AS patient_key,
        e.icu_encounter_key AS icu_encounter_key
    FROM icu_encounter e
    INNER JOIN patient p
        ON e.patient_key = p.patient_key
    WHERE e.stay_id_str IS NOT NULL
), aggregated AS (
    SELECT
        i.subject_id,
        i.stay_id,
        i.patient_key,
        i.icu_encounter_key,
        MIN(bg.lactate) AS lactate_min,
        MAX(bg.lactate) AS lactate_max,
        MIN(bg.ph) AS ph_min,
        MAX(bg.ph) AS ph_max,
        MIN(bg.so2) AS so2_min,
        MAX(bg.so2) AS so2_max,
        MIN(bg.po2) AS po2_min,
        MAX(bg.po2) AS po2_max,
        MIN(bg.pco2) AS pco2_min,
        MAX(bg.pco2) AS pco2_max,
        MIN(bg.aado2) AS aado2_min,
        MAX(bg.aado2) AS aado2_max,
        MIN(bg.aado2_calc) AS aado2_calc_min,
        MAX(bg.aado2_calc) AS aado2_calc_max,
        MIN(bg.pao2fio2ratio) AS pao2fio2ratio_min,
        MAX(bg.pao2fio2ratio) AS pao2fio2ratio_max,
        MIN(bg.baseexcess) AS baseexcess_min,
        MAX(bg.baseexcess) AS baseexcess_max,
        MIN(bg.bicarbonate) AS bicarbonate_min,
        MAX(bg.bicarbonate) AS bicarbonate_max,
        MIN(bg.totalco2) AS totalco2_min,
        MAX(bg.totalco2) AS totalco2_max,
        MIN(bg.hematocrit) AS hematocrit_min,
        MAX(bg.hematocrit) AS hematocrit_max,
        MIN(bg.hemoglobin) AS hemoglobin_min,
        MAX(bg.hemoglobin) AS hemoglobin_max,
        MIN(bg.carboxyhemoglobin) AS carboxyhemoglobin_min,
        MAX(bg.carboxyhemoglobin) AS carboxyhemoglobin_max,
        MIN(bg.methemoglobin) AS methemoglobin_min,
        MAX(bg.methemoglobin) AS methemoglobin_max,
        MIN(bg.temperature) AS temperature_min,
        MAX(bg.temperature) AS temperature_max,
        MIN(bg.chloride) AS chloride_min,
        MAX(bg.chloride) AS chloride_max,
        MIN(bg.calcium) AS calcium_min,
        MAX(bg.calcium) AS calcium_max,
        MIN(bg.glucose) AS glucose_min,
        MAX(bg.glucose) AS glucose_max,
        MIN(bg.potassium) AS potassium_min,
        MAX(bg.potassium) AS potassium_max,
        MIN(bg.sodium) AS sodium_min,
        MAX(bg.sodium) AS sodium_max
    FROM icu i
    LEFT JOIN bg
        ON i.patient_key = bg.patient_key
        AND bg.specimen = 'ART.'
        AND bg.charttime >= i.intime - INTERVAL 6 HOURS
        AND bg.charttime <= i.intime + INTERVAL 1 DAY
    GROUP BY
        i.subject_id,
        i.stay_id,
        i.patient_key,
        i.icu_encounter_key
)
SELECT
    CAST(a.subject_id AS INTEGER) AS subject_id,
    CAST(a.stay_id AS INTEGER) AS stay_id,
    CAST(a.lactate_min AS DOUBLE) AS lactate_min,
    CAST(a.lactate_max AS DOUBLE) AS lactate_max,
    CAST(a.ph_min AS DOUBLE) AS ph_min,
    CAST(a.ph_max AS DOUBLE) AS ph_max,
    CAST(a.so2_min AS DOUBLE) AS so2_min,
    CAST(a.so2_max AS DOUBLE) AS so2_max,
    CAST(a.po2_min AS DOUBLE) AS po2_min,
    CAST(a.po2_max AS DOUBLE) AS po2_max,
    CAST(a.pco2_min AS DOUBLE) AS pco2_min,
    CAST(a.pco2_max AS DOUBLE) AS pco2_max,
    CAST(a.aado2_min AS DOUBLE) AS aado2_min,
    CAST(a.aado2_max AS DOUBLE) AS aado2_max,
    CAST(a.aado2_calc_min AS DECIMAL(38,4)) AS aado2_calc_min,
    CAST(a.aado2_calc_max AS DECIMAL(38,4)) AS aado2_calc_max,
    CAST(a.pao2fio2ratio_min AS DOUBLE) AS pao2fio2ratio_min,
    CAST(a.pao2fio2ratio_max AS DOUBLE) AS pao2fio2ratio_max,
    CAST(a.baseexcess_min AS DOUBLE) AS baseexcess_min,
    CAST(a.baseexcess_max AS DOUBLE) AS baseexcess_max,
    CAST(a.bicarbonate_min AS DOUBLE) AS bicarbonate_min,
    CAST(a.bicarbonate_max AS DOUBLE) AS bicarbonate_max,
    CAST(a.totalco2_min AS DOUBLE) AS totalco2_min,
    CAST(a.totalco2_max AS DOUBLE) AS totalco2_max,
    CAST(a.hematocrit_min AS DOUBLE) AS hematocrit_min,
    CAST(a.hematocrit_max AS DOUBLE) AS hematocrit_max,
    CAST(a.hemoglobin_min AS DOUBLE) AS hemoglobin_min,
    CAST(a.hemoglobin_max AS DOUBLE) AS hemoglobin_max,
    CAST(a.carboxyhemoglobin_min AS DOUBLE) AS carboxyhemoglobin_min,
    CAST(a.carboxyhemoglobin_max AS DOUBLE) AS carboxyhemoglobin_max,
    CAST(a.methemoglobin_min AS DOUBLE) AS methemoglobin_min,
    CAST(a.methemoglobin_max AS DOUBLE) AS methemoglobin_max,
    CAST(a.temperature_min AS DOUBLE) AS temperature_min,
    CAST(a.temperature_max AS DOUBLE) AS temperature_max,
    CAST(a.chloride_min AS DOUBLE) AS chloride_min,
    CAST(a.chloride_max AS DOUBLE) AS chloride_max,
    CAST(a.calcium_min AS DOUBLE) AS calcium_min,
    CAST(a.calcium_max AS DOUBLE) AS calcium_max,
    CAST(a.glucose_min AS DOUBLE) AS glucose_min,
    CAST(a.glucose_max AS DOUBLE) AS glucose_max,
    CAST(a.potassium_min AS DOUBLE) AS potassium_min,
    CAST(a.potassium_max AS DOUBLE) AS potassium_max,
    CAST(a.sodium_min AS DOUBLE) AS sodium_min,
    CAST(a.sodium_max AS DOUBLE) AS sodium_max,
    a.patient_key,
    a.icu_encounter_key
FROM aggregated a
;
