-- Readability copy -- not the artifact a server loads.
--
-- Library.first_day_lab.json in this directory is authoritative. This SQL is
-- the decoded form of its content.data, byte-identical to the sql-text
-- extension beside it. Edit neither: both are generated by
-- `mimic-utils metrics-finalize` from the finalized attempt.

WITH icu AS (
    SELECT
        CAST(p.subject_id_str AS INTEGER) AS subject_id,
        CAST(e.stay_id_str AS INTEGER) AS stay_id,
        TRY_CAST(e.intime AS TIMESTAMP_NTZ) AS intime,
        p.patient_key,
        e.icu_encounter_key
    FROM icu_encounter e
    INNER JOIN patient p
        ON e.patient_key = p.patient_key
    WHERE e.stay_id_str IS NOT NULL
), cbc AS (
    SELECT
        i.stay_id,
        MIN(le.hematocrit) AS hematocrit_min,
        MAX(le.hematocrit) AS hematocrit_max,
        MIN(le.hemoglobin) AS hemoglobin_min,
        MAX(le.hemoglobin) AS hemoglobin_max,
        MIN(le.platelet) AS platelets_min,
        MAX(le.platelet) AS platelets_max,
        MIN(le.wbc) AS wbc_min,
        MAX(le.wbc) AS wbc_max
    FROM icu i
    LEFT JOIN complete_blood_count le
        ON le.patient_key = i.patient_key
        AND le.charttime >= i.intime - INTERVAL 6 HOURS
        AND le.charttime <= i.intime + INTERVAL 1 DAY
    GROUP BY i.stay_id
), chem AS (
    SELECT
        i.stay_id,
        MIN(le.albumin) AS albumin_min,
        MAX(le.albumin) AS albumin_max,
        MIN(le.globulin) AS globulin_min,
        MAX(le.globulin) AS globulin_max,
        MIN(le.total_protein) AS total_protein_min,
        MAX(le.total_protein) AS total_protein_max,
        MIN(le.aniongap) AS aniongap_min,
        MAX(le.aniongap) AS aniongap_max,
        MIN(le.bicarbonate) AS bicarbonate_min,
        MAX(le.bicarbonate) AS bicarbonate_max,
        MIN(le.bun) AS bun_min,
        MAX(le.bun) AS bun_max,
        MIN(le.calcium) AS calcium_min,
        MAX(le.calcium) AS calcium_max,
        MIN(le.chloride) AS chloride_min,
        MAX(le.chloride) AS chloride_max,
        MIN(le.creatinine) AS creatinine_min,
        MAX(le.creatinine) AS creatinine_max,
        MIN(le.glucose) AS glucose_min,
        MAX(le.glucose) AS glucose_max,
        MIN(le.sodium) AS sodium_min,
        MAX(le.sodium) AS sodium_max,
        MIN(le.potassium) AS potassium_min,
        MAX(le.potassium) AS potassium_max
    FROM icu i
    LEFT JOIN chemistry le
        ON le.patient_key = i.patient_key
        AND le.charttime >= i.intime - INTERVAL 6 HOURS
        AND le.charttime <= i.intime + INTERVAL 1 DAY
    GROUP BY i.stay_id
), diff AS (
    SELECT
        i.stay_id,
        MIN(le.basophils_abs) AS abs_basophils_min,
        MAX(le.basophils_abs) AS abs_basophils_max,
        MIN(le.eosinophils_abs) AS abs_eosinophils_min,
        MAX(le.eosinophils_abs) AS abs_eosinophils_max,
        MIN(le.lymphocytes_abs) AS abs_lymphocytes_min,
        MAX(le.lymphocytes_abs) AS abs_lymphocytes_max,
        MIN(le.monocytes_abs) AS abs_monocytes_min,
        MAX(le.monocytes_abs) AS abs_monocytes_max,
        MIN(le.neutrophils_abs) AS abs_neutrophils_min,
        MAX(le.neutrophils_abs) AS abs_neutrophils_max,
        MIN(le.atypical_lymphocytes) AS atyps_min,
        MAX(le.atypical_lymphocytes) AS atyps_max,
        MIN(le.bands) AS bands_min,
        MAX(le.bands) AS bands_max,
        MIN(le.immature_granulocytes) AS imm_granulocytes_min,
        MAX(le.immature_granulocytes) AS imm_granulocytes_max,
        MIN(le.metamyelocytes) AS metas_min,
        MAX(le.metamyelocytes) AS metas_max,
        MIN(le.nrbc) AS nrbc_min,
        MAX(le.nrbc) AS nrbc_max
    FROM icu i
    LEFT JOIN blood_differential le
        ON le.patient_key = i.patient_key
        AND le.charttime >= i.intime - INTERVAL 6 HOURS
        AND le.charttime <= i.intime + INTERVAL 1 DAY
    GROUP BY i.stay_id
), coag AS (
    SELECT
        i.stay_id,
        MIN(le.d_dimer) AS d_dimer_min,
        MAX(le.d_dimer) AS d_dimer_max,
        MIN(le.fibrinogen) AS fibrinogen_min,
        MAX(le.fibrinogen) AS fibrinogen_max,
        MIN(le.thrombin) AS thrombin_min,
        MAX(le.thrombin) AS thrombin_max,
        MIN(le.inr) AS inr_min,
        MAX(le.inr) AS inr_max,
        MIN(le.pt) AS pt_min,
        MAX(le.pt) AS pt_max,
        MIN(le.ptt) AS ptt_min,
        MAX(le.ptt) AS ptt_max
    FROM icu i
    LEFT JOIN coagulation le
        ON le.patient_key = i.patient_key
        AND le.charttime >= i.intime - INTERVAL 6 HOURS
        AND le.charttime <= i.intime + INTERVAL 1 DAY
    GROUP BY i.stay_id
), enz AS (
    SELECT
        i.stay_id,
        MIN(le.alt) AS alt_min,
        MAX(le.alt) AS alt_max,
        MIN(le.alp) AS alp_min,
        MAX(le.alp) AS alp_max,
        MIN(le.ast) AS ast_min,
        MAX(le.ast) AS ast_max,
        MIN(le.amylase) AS amylase_min,
        MAX(le.amylase) AS amylase_max,
        MIN(le.bilirubin_total) AS bilirubin_total_min,
        MAX(le.bilirubin_total) AS bilirubin_total_max,
        MIN(le.bilirubin_direct) AS bilirubin_direct_min,
        MAX(le.bilirubin_direct) AS bilirubin_direct_max,
        MIN(le.bilirubin_indirect) AS bilirubin_indirect_min,
        MAX(le.bilirubin_indirect) AS bilirubin_indirect_max,
        MIN(le.ck_cpk) AS ck_cpk_min,
        MAX(le.ck_cpk) AS ck_cpk_max,
        MIN(le.ck_mb) AS ck_mb_min,
        MAX(le.ck_mb) AS ck_mb_max,
        MIN(le.ggt) AS ggt_min,
        MAX(le.ggt) AS ggt_max,
        MIN(le.ld_ldh) AS ld_ldh_min,
        MAX(le.ld_ldh) AS ld_ldh_max
    FROM icu i
    LEFT JOIN enzyme le
        ON le.patient_key = i.patient_key
        AND le.charttime >= i.intime - INTERVAL 6 HOURS
        AND le.charttime <= i.intime + INTERVAL 1 DAY
    GROUP BY i.stay_id
)
SELECT
    CAST(cbc.hematocrit_min AS DOUBLE) AS hematocrit_min,
    CAST(cbc.hematocrit_max AS DOUBLE) AS hematocrit_max,
    CAST(cbc.hemoglobin_min AS DOUBLE) AS hemoglobin_min,
    CAST(cbc.hemoglobin_max AS DOUBLE) AS hemoglobin_max,
    CAST(cbc.platelets_min AS DOUBLE) AS platelets_min,
    CAST(cbc.platelets_max AS DOUBLE) AS platelets_max,
    CAST(cbc.wbc_min AS DOUBLE) AS wbc_min,
    CAST(cbc.wbc_max AS DOUBLE) AS wbc_max,
    CAST(chem.albumin_min AS DOUBLE) AS albumin_min,
    CAST(chem.albumin_max AS DOUBLE) AS albumin_max,
    CAST(chem.globulin_min AS DOUBLE) AS globulin_min,
    CAST(chem.globulin_max AS DOUBLE) AS globulin_max,
    CAST(chem.total_protein_min AS DOUBLE) AS total_protein_min,
    CAST(chem.total_protein_max AS DOUBLE) AS total_protein_max,
    CAST(chem.aniongap_min AS DOUBLE) AS aniongap_min,
    CAST(chem.aniongap_max AS DOUBLE) AS aniongap_max,
    CAST(chem.bicarbonate_min AS DOUBLE) AS bicarbonate_min,
    CAST(chem.bicarbonate_max AS DOUBLE) AS bicarbonate_max,
    CAST(chem.bun_min AS DOUBLE) AS bun_min,
    CAST(chem.bun_max AS DOUBLE) AS bun_max,
    CAST(chem.calcium_min AS DOUBLE) AS calcium_min,
    CAST(chem.calcium_max AS DOUBLE) AS calcium_max,
    CAST(chem.chloride_min AS DOUBLE) AS chloride_min,
    CAST(chem.chloride_max AS DOUBLE) AS chloride_max,
    CAST(chem.creatinine_min AS DOUBLE) AS creatinine_min,
    CAST(chem.creatinine_max AS DOUBLE) AS creatinine_max,
    CAST(chem.glucose_min AS DOUBLE) AS glucose_min,
    CAST(chem.glucose_max AS DOUBLE) AS glucose_max,
    CAST(chem.sodium_min AS DOUBLE) AS sodium_min,
    CAST(chem.sodium_max AS DOUBLE) AS sodium_max,
    CAST(chem.potassium_min AS DOUBLE) AS potassium_min,
    CAST(chem.potassium_max AS DOUBLE) AS potassium_max,
    CAST(diff.abs_basophils_min AS DECIMAL(38,4)) AS abs_basophils_min,
    CAST(diff.abs_basophils_max AS DECIMAL(38,4)) AS abs_basophils_max,
    CAST(diff.abs_eosinophils_min AS DECIMAL(38,4)) AS abs_eosinophils_min,
    CAST(diff.abs_eosinophils_max AS DECIMAL(38,4)) AS abs_eosinophils_max,
    CAST(diff.abs_lymphocytes_min AS DECIMAL(38,4)) AS abs_lymphocytes_min,
    CAST(diff.abs_lymphocytes_max AS DECIMAL(38,4)) AS abs_lymphocytes_max,
    CAST(diff.abs_monocytes_min AS DECIMAL(38,4)) AS abs_monocytes_min,
    CAST(diff.abs_monocytes_max AS DECIMAL(38,4)) AS abs_monocytes_max,
    CAST(diff.abs_neutrophils_min AS DECIMAL(38,4)) AS abs_neutrophils_min,
    CAST(diff.abs_neutrophils_max AS DECIMAL(38,4)) AS abs_neutrophils_max,
    CAST(diff.atyps_min AS DOUBLE) AS atyps_min,
    CAST(diff.atyps_max AS DOUBLE) AS atyps_max,
    CAST(diff.bands_min AS DOUBLE) AS bands_min,
    CAST(diff.bands_max AS DOUBLE) AS bands_max,
    CAST(diff.imm_granulocytes_min AS DOUBLE) AS imm_granulocytes_min,
    CAST(diff.imm_granulocytes_max AS DOUBLE) AS imm_granulocytes_max,
    CAST(diff.metas_min AS DOUBLE) AS metas_min,
    CAST(diff.metas_max AS DOUBLE) AS metas_max,
    CAST(diff.nrbc_min AS DOUBLE) AS nrbc_min,
    CAST(diff.nrbc_max AS DOUBLE) AS nrbc_max,
    CAST(coag.d_dimer_min AS DOUBLE) AS d_dimer_min,
    CAST(coag.d_dimer_max AS DOUBLE) AS d_dimer_max,
    CAST(coag.fibrinogen_min AS DOUBLE) AS fibrinogen_min,
    CAST(coag.fibrinogen_max AS DOUBLE) AS fibrinogen_max,
    CAST(coag.thrombin_min AS DOUBLE) AS thrombin_min,
    CAST(coag.thrombin_max AS DOUBLE) AS thrombin_max,
    CAST(coag.inr_min AS DOUBLE) AS inr_min,
    CAST(coag.inr_max AS DOUBLE) AS inr_max,
    CAST(coag.pt_min AS DOUBLE) AS pt_min,
    CAST(coag.pt_max AS DOUBLE) AS pt_max,
    CAST(coag.ptt_min AS DOUBLE) AS ptt_min,
    CAST(coag.ptt_max AS DOUBLE) AS ptt_max,
    CAST(enz.alt_min AS DOUBLE) AS alt_min,
    CAST(enz.alt_max AS DOUBLE) AS alt_max,
    CAST(enz.alp_min AS DOUBLE) AS alp_min,
    CAST(enz.alp_max AS DOUBLE) AS alp_max,
    CAST(enz.ast_min AS DOUBLE) AS ast_min,
    CAST(enz.ast_max AS DOUBLE) AS ast_max,
    CAST(enz.amylase_min AS DOUBLE) AS amylase_min,
    CAST(enz.amylase_max AS DOUBLE) AS amylase_max,
    CAST(enz.bilirubin_total_min AS DOUBLE) AS bilirubin_total_min,
    CAST(enz.bilirubin_total_max AS DOUBLE) AS bilirubin_total_max,
    CAST(enz.bilirubin_direct_min AS DOUBLE) AS bilirubin_direct_min,
    CAST(enz.bilirubin_direct_max AS DOUBLE) AS bilirubin_direct_max,
    CAST(enz.bilirubin_indirect_min AS DOUBLE) AS bilirubin_indirect_min,
    CAST(enz.bilirubin_indirect_max AS DOUBLE) AS bilirubin_indirect_max,
    CAST(enz.ck_cpk_min AS DOUBLE) AS ck_cpk_min,
    CAST(enz.ck_cpk_max AS DOUBLE) AS ck_cpk_max,
    CAST(enz.ck_mb_min AS DOUBLE) AS ck_mb_min,
    CAST(enz.ck_mb_max AS DOUBLE) AS ck_mb_max,
    CAST(enz.ggt_min AS DOUBLE) AS ggt_min,
    CAST(enz.ggt_max AS DOUBLE) AS ggt_max,
    CAST(enz.ld_ldh_min AS DOUBLE) AS ld_ldh_min,
    CAST(enz.ld_ldh_max AS DOUBLE) AS ld_ldh_max,
    i.icu_encounter_key,
    i.patient_key
FROM icu i
LEFT JOIN cbc
    ON i.stay_id = cbc.stay_id
LEFT JOIN chem
    ON i.stay_id = chem.stay_id
LEFT JOIN diff
    ON i.stay_id = diff.stay_id
LEFT JOIN coag
    ON i.stay_id = coag.stay_id
LEFT JOIN enz
    ON i.stay_id = enz.stay_id
;
