-- Readability copy -- not the artifact a server loads.
--
-- Library.invasive_line.json in this directory is authoritative. This SQL is
-- the decoded form of its content.data, byte-identical to the sql-text
-- extension beside it. Edit neither: both are generated by
-- `mimic-utils metrics-finalize` from the finalized attempt.

WITH selected_procedures AS (
    SELECT
        p.patient_key,
        p.encounter_key,
        p.item_code,
        p.item_system,
        p.item_display,
        p.site_code,
        p.site_system,
        p.performed_datetime,
        p.performed_period_start,
        p.performed_period_end
    FROM invasive_line_procedure p
    WHERE p.item_system = 'http://mimic.mit.edu/fhir/mimic/CodeSystem/mimic-d-items'
      AND p.item_code IN (
          '227719', '225752', '224269', '224267', '224270', '224272',
          '226124', '228169', '225202', '228286', '225204', '224263',
          '224560', '224264', '225203', '224273', '225789', '225761',
          '228201', '228202', '224268', '225199', '225315', '225205'
      )
), typed_procedures AS (
    SELECT
        e.stay_id_str,
        p.patient_key,
        e.encounter_key AS icu_encounter_key,
        CASE
            WHEN p.item_display IN ('Arterial Line', 'A-Line') THEN 'Arterial'
            WHEN p.item_display IN ('CCO PA Line', 'CCO PAC')
                THEN 'Continuous Cardiac Output PA'
            WHEN p.item_display IN ('Dialysis Catheter', 'Dialysis Line')
                THEN 'Dialysis'
            WHEN p.item_display IN ('Hickman', 'Tunneled (Hickman) Line')
                THEN 'Hickman'
            WHEN p.item_display IN ('IABP', 'IABP line') THEN 'IABP'
            WHEN p.item_display IN ('Multi Lumen', 'Multi-lumen')
                THEN 'Multi Lumen'
            WHEN p.item_display IN ('PA Catheter', 'PA line') THEN 'PA'
            WHEN p.item_display IN ('PICC Line', 'PICC line') THEN 'PICC'
            WHEN p.item_display IN ('Pre-Sep Catheter', 'Presep Catheter')
                THEN 'Pre-Sep'
            WHEN p.item_display IN ('Trauma Line', 'Trauma line') THEN 'Trauma'
            WHEN p.item_display IN ('Triple Introducer', 'TripleIntroducer')
                THEN 'Triple Introducer'
            WHEN p.item_display IN ('Portacath', 'Indwelling Port (PortaCath)')
                THEN 'Portacath'
            ELSE p.item_display
        END AS line_type,
        CASE
            WHEN p.site_code IN ('Left Antecub', 'Left Antecube')
                THEN 'Left Antecube'
            WHEN p.site_code IN ('Left Axilla', 'Left Axilla.')
                THEN 'Left Axilla'
            WHEN p.site_code IN ('Left Brachial', 'Left Brachial.')
                THEN 'Left Brachial'
            WHEN p.site_code IN ('Left Femoral', 'Left Femoral.')
                THEN 'Left Femoral'
            WHEN p.site_code IN ('Right Antecub', 'Right Antecube')
                THEN 'Right Antecube'
            WHEN p.site_code IN ('Right Axilla', 'Right Axilla.')
                THEN 'Right Axilla'
            WHEN p.site_code IN ('Right Brachial', 'Right Brachial.')
                THEN 'Right Brachial'
            WHEN p.site_code IN ('Right Femoral', 'Right Femoral.')
                THEN 'Right Femoral'
            ELSE p.site_code
        END AS line_site,
        COALESCE(
            TRY_CAST(p.performed_datetime AS TIMESTAMP_NTZ),
            TRY_CAST(p.performed_period_start AS TIMESTAMP_NTZ)
        ) AS starttime,
        COALESCE(
            TRY_CAST(p.performed_datetime AS TIMESTAMP_NTZ),
            TRY_CAST(p.performed_period_end AS TIMESTAMP_NTZ)
        ) AS endtime
    FROM selected_procedures p
    INNER JOIN invasive_line_icu_encounter e
        ON p.encounter_key = e.encounter_key
    WHERE e.stay_id_str IS NOT NULL
)
SELECT
    CAST(line_type AS VARCHAR(255)) AS line_type,
    CAST(line_site AS VARCHAR(255)) AS line_site,
    CAST(starttime AS TIMESTAMP_NTZ) AS starttime,
    CAST(endtime AS TIMESTAMP_NTZ) AS endtime,
    icu_encounter_key AS icu_encounter_key,
    patient_key AS patient_key
FROM typed_procedures;
