-- Readability copy -- not the artifact a server loads.
--
-- Library.sofa.json in this directory is authoritative. This SQL is
-- the decoded form of its content.data, byte-identical to the sql-text
-- extension beside it. Edit neither: both are generated by
-- `mimic-utils metrics-finalize` from the finalized attempt.

WITH icu AS (
    SELECT
        i.icu_encounter_key,
        i.patient_key,
        i.parent_encounter_key,
        i.stay_system,
        i.stay_id_str
    FROM icu_encounter AS i
    WHERE i.stay_system = 'http://mimic.mit.edu/fhir/mimic/identifier/encounter-icu'
        AND i.stay_id_str IS NOT NULL
), co AS (
    SELECT
        ih.icu_encounter_key,
        ih.patient_key,
        i.parent_encounter_key AS encounter_key,
        CAST(i.stay_id_str AS INTEGER) AS stay_id,
        ih.hr,
        ih.endtime - INTERVAL 1 HOUR AS starttime,
        ih.endtime
    FROM icustay_hourly AS ih
    INNER JOIN icu AS i
        ON ih.icu_encounter_key = i.icu_encounter_key
), pafi AS (
    SELECT
        i.icu_encounter_key,
        bg.charttime,
        CASE
            WHEN vd.icu_encounter_key IS NULL THEN bg.pao2fio2ratio
            ELSE NULL
        END AS pao2fio2ratio_novent,
        CASE
            WHEN vd.icu_encounter_key IS NOT NULL THEN bg.pao2fio2ratio
            ELSE NULL
        END AS pao2fio2ratio_vent
    FROM icu AS i
    INNER JOIN bg AS bg
        ON i.patient_key = bg.patient_key
    LEFT JOIN ventilation AS vd
        ON i.icu_encounter_key = vd.icu_encounter_key
        AND bg.charttime >= vd.starttime
        AND bg.charttime <= vd.endtime
        AND vd.ventilation_status = 'InvasiveVent'
    WHERE bg.specimen = 'ART.'
), vs AS (
    SELECT
        co.stay_id,
        co.hr,
        MIN(v.mbp) AS meanbp_min
    FROM co
    LEFT JOIN vitalsign AS v
        ON co.icu_encounter_key = v.icu_encounter_key
        AND co.starttime < v.charttime
        AND co.endtime >= v.charttime
    GROUP BY co.stay_id, co.hr
), gcs_hourly AS (
    SELECT
        co.stay_id,
        co.hr,
        MIN(g.gcs) AS gcs_min
    FROM co
    LEFT JOIN gcs AS g
        ON co.icu_encounter_key = g.icu_encounter_key
        AND co.starttime < g.charttime
        AND co.endtime >= g.charttime
    GROUP BY co.stay_id, co.hr
), bili AS (
    SELECT
        co.stay_id,
        co.hr,
        MAX(enz.bilirubin_total) AS bilirubin_max
    FROM co
    LEFT JOIN enzyme AS enz
        ON co.encounter_key = enz.encounter_key
        AND co.starttime < enz.charttime
        AND co.endtime >= enz.charttime
    GROUP BY co.stay_id, co.hr
), cr AS (
    SELECT
        co.stay_id,
        co.hr,
        MAX(chem.creatinine) AS creatinine_max
    FROM co
    LEFT JOIN chemistry AS chem
        ON co.encounter_key = chem.encounter_key
        AND co.starttime < chem.charttime
        AND co.endtime >= chem.charttime
    GROUP BY co.stay_id, co.hr
), plt AS (
    SELECT
        co.stay_id,
        co.hr,
        MIN(cbc.platelet) AS platelet_min
    FROM co
    LEFT JOIN complete_blood_count AS cbc
        ON co.encounter_key = cbc.encounter_key
        AND co.starttime < cbc.charttime
        AND co.endtime >= cbc.charttime
    GROUP BY co.stay_id, co.hr
), pf AS (
    SELECT
        co.stay_id,
        co.hr,
        MIN(p.pao2fio2ratio_novent) AS pao2fio2ratio_novent,
        MIN(p.pao2fio2ratio_vent) AS pao2fio2ratio_vent
    FROM co
    LEFT JOIN pafi AS p
        ON co.icu_encounter_key = p.icu_encounter_key
        AND co.starttime < p.charttime
        AND co.endtime >= p.charttime
    GROUP BY co.stay_id, co.hr
), uo AS (
    SELECT
        co.stay_id,
        co.hr,
        MAX(
            CASE
                WHEN u.uo_tm_24hr >= 22 AND u.uo_tm_24hr <= 30
                    THEN u.urineoutput_24hr / u.uo_tm_24hr * 24
            END
        ) AS uo_24hr
    FROM co
    LEFT JOIN urine_output_rate AS u
        ON co.icu_encounter_key = u.icu_encounter_key
        AND co.starttime < u.charttime
        AND co.endtime >= u.charttime
    GROUP BY co.stay_id, co.hr
), vaso AS (
    SELECT
        co.stay_id,
        co.hr,
        MAX(epi.vaso_rate) AS rate_epinephrine,
        MAX(nor.vaso_rate) AS rate_norepinephrine,
        MAX(dop.vaso_rate) AS rate_dopamine,
        MAX(dob.vaso_rate) AS rate_dobutamine
    FROM co
    LEFT JOIN epinephrine AS epi
        ON co.icu_encounter_key = epi.icu_encounter_key
        AND co.endtime > epi.starttime
        AND co.endtime <= epi.endtime
    LEFT JOIN norepinephrine AS nor
        ON co.icu_encounter_key = nor.icu_encounter_key
        AND co.endtime > nor.starttime
        AND co.endtime <= nor.endtime
    LEFT JOIN dopamine AS dop
        ON co.icu_encounter_key = dop.icu_encounter_key
        AND co.endtime > dop.starttime
        AND co.endtime <= dop.endtime
    LEFT JOIN dobutamine AS dob
        ON co.icu_encounter_key = dob.icu_encounter_key
        AND co.endtime > dob.starttime
        AND co.endtime <= dob.endtime
    WHERE epi.icu_encounter_key IS NOT NULL
        OR nor.icu_encounter_key IS NOT NULL
        OR dop.icu_encounter_key IS NOT NULL
        OR dob.icu_encounter_key IS NOT NULL
    GROUP BY co.stay_id, co.hr
), scorecomp AS (
    SELECT
        co.stay_id,
        co.hr,
        co.starttime,
        co.endtime,
        pf.pao2fio2ratio_novent,
        pf.pao2fio2ratio_vent,
        vaso.rate_epinephrine,
        vaso.rate_norepinephrine,
        vaso.rate_dopamine,
        vaso.rate_dobutamine,
        vs.meanbp_min,
        gcs_hourly.gcs_min,
        uo.uo_24hr,
        bili.bilirubin_max,
        cr.creatinine_max,
        plt.platelet_min,
        co.icu_encounter_key,
        co.patient_key
    FROM co
    LEFT JOIN vs
        ON co.stay_id = vs.stay_id
        AND co.hr = vs.hr
    LEFT JOIN gcs_hourly
        ON co.stay_id = gcs_hourly.stay_id
        AND co.hr = gcs_hourly.hr
    LEFT JOIN bili
        ON co.stay_id = bili.stay_id
        AND co.hr = bili.hr
    LEFT JOIN cr
        ON co.stay_id = cr.stay_id
        AND co.hr = cr.hr
    LEFT JOIN plt
        ON co.stay_id = plt.stay_id
        AND co.hr = plt.hr
    LEFT JOIN pf
        ON co.stay_id = pf.stay_id
        AND co.hr = pf.hr
    LEFT JOIN uo
        ON co.stay_id = uo.stay_id
        AND co.hr = uo.hr
    LEFT JOIN vaso
        ON co.stay_id = vaso.stay_id
        AND co.hr = vaso.hr
), scorecalc AS (
    SELECT
        scorecomp.*,
        CASE
            WHEN pao2fio2ratio_vent < 100 THEN 4
            WHEN pao2fio2ratio_vent < 200 THEN 3
            WHEN pao2fio2ratio_novent < 300 THEN 2
            WHEN pao2fio2ratio_vent < 300 THEN 2
            WHEN pao2fio2ratio_novent < 400 THEN 1
            WHEN pao2fio2ratio_vent < 400 THEN 1
            WHEN COALESCE(pao2fio2ratio_vent, pao2fio2ratio_novent) IS NULL THEN NULL
            ELSE 0
        END AS respiration,
        CASE
            WHEN platelet_min < 20 THEN 4
            WHEN platelet_min < 50 THEN 3
            WHEN platelet_min < 100 THEN 2
            WHEN platelet_min < 150 THEN 1
            WHEN platelet_min IS NULL THEN NULL
            ELSE 0
        END AS coagulation,
        CASE
            WHEN bilirubin_max >= 12.0 THEN 4
            WHEN bilirubin_max >= 6.0 THEN 3
            WHEN bilirubin_max >= 2.0 THEN 2
            WHEN bilirubin_max >= 1.2 THEN 1
            WHEN bilirubin_max IS NULL THEN NULL
            ELSE 0
        END AS liver,
        CASE
            WHEN rate_dopamine > CAST(15 AS FLOAT)
                OR rate_epinephrine > CAST(0.1 AS FLOAT)
                OR rate_norepinephrine > CAST(0.1 AS FLOAT)
                THEN 4
            WHEN rate_dopamine > CAST(5 AS FLOAT)
                OR rate_epinephrine <= CAST(0.1 AS FLOAT)
                OR rate_norepinephrine <= CAST(0.1 AS FLOAT)
                THEN 3
            WHEN rate_dopamine > CAST(0 AS FLOAT)
                OR rate_dobutamine > CAST(0 AS FLOAT)
                THEN 2
            WHEN meanbp_min < 70 THEN 1
            WHEN COALESCE(
                meanbp_min,
                rate_dopamine,
                rate_dobutamine,
                rate_epinephrine,
                rate_norepinephrine
            ) IS NULL THEN NULL
            ELSE 0
        END AS cardiovascular,
        CASE
            WHEN gcs_min >= 13 AND gcs_min <= 14 THEN 1
            WHEN gcs_min >= 10 AND gcs_min <= 12 THEN 2
            WHEN gcs_min >= 6 AND gcs_min <= 9 THEN 3
            WHEN gcs_min < 6 THEN 4
            WHEN gcs_min IS NULL THEN NULL
            ELSE 0
        END AS cns,
        CASE
            WHEN creatinine_max >= 5.0 THEN 4
            WHEN uo_24hr < 200 THEN 4
            WHEN creatinine_max >= 3.5 AND creatinine_max < 5.0 THEN 3
            WHEN uo_24hr < 500 THEN 3
            WHEN creatinine_max >= 2.0 AND creatinine_max < 3.5 THEN 2
            WHEN creatinine_max >= 1.2 AND creatinine_max < 2.0 THEN 1
            WHEN COALESCE(uo_24hr, creatinine_max) IS NULL THEN NULL
            ELSE 0
        END AS renal
    FROM scorecomp
), score_final AS (
    SELECT
        s.*,
        COALESCE(MAX(respiration) OVER w, 0) AS respiration_24hours,
        COALESCE(MAX(coagulation) OVER w, 0) AS coagulation_24hours,
        COALESCE(MAX(liver) OVER w, 0) AS liver_24hours,
        COALESCE(MAX(cardiovascular) OVER w, 0) AS cardiovascular_24hours,
        COALESCE(MAX(cns) OVER w, 0) AS cns_24hours,
        COALESCE(MAX(renal) OVER w, 0) AS renal_24hours,
        COALESCE(MAX(respiration) OVER w, 0)
            + COALESCE(MAX(coagulation) OVER w, 0)
            + COALESCE(MAX(liver) OVER w, 0)
            + COALESCE(MAX(cardiovascular) OVER w, 0)
            + COALESCE(MAX(cns) OVER w, 0)
            + COALESCE(MAX(renal) OVER w, 0) AS sofa_24hours
    FROM scorecalc AS s
    WINDOW w AS (
        PARTITION BY stay_id
        ORDER BY hr
        ROWS BETWEEN 23 PRECEDING AND 0 FOLLOWING
    )
)
SELECT
    CAST(sf.hr AS BIGINT) AS hr,
    CAST(sf.starttime AS TIMESTAMP_NTZ) AS starttime,
    CAST(sf.endtime AS TIMESTAMP_NTZ) AS endtime,
    CAST(sf.pao2fio2ratio_novent AS DOUBLE) AS pao2fio2ratio_novent,
    CAST(sf.pao2fio2ratio_vent AS DOUBLE) AS pao2fio2ratio_vent,
    CAST(sf.rate_epinephrine AS FLOAT) AS rate_epinephrine,
    CAST(sf.rate_norepinephrine AS FLOAT) AS rate_norepinephrine,
    CAST(sf.rate_dopamine AS FLOAT) AS rate_dopamine,
    CAST(sf.rate_dobutamine AS FLOAT) AS rate_dobutamine,
    CAST(sf.meanbp_min AS DOUBLE) AS meanbp_min,
    CAST(sf.gcs_min AS FLOAT) AS gcs_min,
    CAST(sf.uo_24hr AS DOUBLE) AS uo_24hr,
    CAST(sf.bilirubin_max AS DOUBLE) AS bilirubin_max,
    CAST(sf.creatinine_max AS DOUBLE) AS creatinine_max,
    CAST(sf.platelet_min AS DOUBLE) AS platelet_min,
    CAST(sf.respiration AS INTEGER) AS respiration,
    CAST(sf.coagulation AS INTEGER) AS coagulation,
    CAST(sf.liver AS INTEGER) AS liver,
    CAST(sf.cardiovascular AS INTEGER) AS cardiovascular,
    CAST(sf.cns AS INTEGER) AS cns,
    CAST(sf.renal AS INTEGER) AS renal,
    CAST(sf.respiration_24hours AS INTEGER) AS respiration_24hours,
    CAST(sf.coagulation_24hours AS INTEGER) AS coagulation_24hours,
    CAST(sf.liver_24hours AS INTEGER) AS liver_24hours,
    CAST(sf.cardiovascular_24hours AS INTEGER) AS cardiovascular_24hours,
    CAST(sf.cns_24hours AS INTEGER) AS cns_24hours,
    CAST(sf.renal_24hours AS INTEGER) AS renal_24hours,
    CAST(sf.sofa_24hours AS INTEGER) AS sofa_24hours,
    sf.icu_encounter_key AS icu_encounter_key,
    sf.patient_key AS patient_key
FROM score_final AS sf
WHERE sf.hr >= 0
;
