-- Readability copy -- not the artifact a server loads.
--
-- Library.creatinine_baseline.json in this directory is authoritative. This SQL is
-- the decoded form of its content.data, byte-identical to the sql-text
-- extension beside it. Edit neither: both are generated by
-- `mimic-utils metrics-finalize` from the finalized attempt.

WITH p AS (
    SELECT
        CAST(eh.hadm_id_str AS INTEGER) AS hadm_id,
        pt.patient_key,
        eh.encounter_key,
        CASE
            WHEN pt.gender_fhir = 'female' THEN 'F'
            WHEN pt.gender_fhir = 'male' THEN 'M'
            ELSE NULL
        END AS gender,
        ag.age,
        CASE
            WHEN pt.gender_fhir = 'female' THEN
                POWER(
                    75.0 / 186.0 / POWER(ag.age, -0.203) / 0.742,
                    -1 / 1.154
                )
            ELSE
                POWER(
                    75.0 / 186.0 / POWER(ag.age, -0.203),
                    -1 / 1.154
                )
        END AS mdrd_est
    FROM age AS ag
    LEFT JOIN patient AS pt
        ON ag.patient_key = pt.patient_key
    LEFT JOIN encounter AS eh
        ON ag.encounter_key = eh.encounter_key
    WHERE ag.age >= 18
), lab AS (
    SELECT
        c.encounter_key,
        MIN(c.creatinine) AS scr_min
    FROM chemistry AS c
    GROUP BY c.encounter_key
), ckd AS (
    SELECT
        CAST(e.hadm_id_str AS INTEGER) AS hadm_id,
        MAX(1) AS ckd_flag
    FROM condition AS c
    INNER JOIN encounter AS e
        ON c.encounter_key = e.encounter_key
    WHERE e.hadm_id_str IS NOT NULL
        AND (
            (
                c.diagnosis_system = 'http://mimic.mit.edu/fhir/mimic/CodeSystem/mimic-diagnosis-icd9'
                AND SUBSTR(c.diagnosis_code, 1, 3) = '585'
            )
            OR (
                c.diagnosis_system = 'http://mimic.mit.edu/fhir/mimic/CodeSystem/mimic-diagnosis-icd10'
                AND SUBSTR(c.diagnosis_code, 1, 3) = 'N18'
            )
        )
    GROUP BY CAST(e.hadm_id_str AS INTEGER)
)
SELECT
    CAST(p.gender AS VARCHAR(255)) AS gender,
    CAST(p.age AS BIGINT) AS age,
    CAST(lab.scr_min AS DOUBLE) AS scr_min,
    CAST(COALESCE(ckd.ckd_flag, 0) AS INTEGER) AS ckd,
    CAST(p.mdrd_est AS DOUBLE) AS mdrd_est,
    CAST(
        CASE
            WHEN lab.scr_min <= 1.1 THEN lab.scr_min
            WHEN ckd.ckd_flag = 1 THEN lab.scr_min
            ELSE p.mdrd_est
        END
        AS DOUBLE
    ) AS scr_baseline,
    p.encounter_key,
    p.patient_key
FROM p
LEFT JOIN lab
    ON p.encounter_key = lab.encounter_key
LEFT JOIN ckd
    ON p.hadm_id = ckd.hadm_id
;
