-- Readability copy -- not the artifact a server loads.
--
-- Library.sepsis3.json in this directory is authoritative. This SQL is
-- the decoded form of its content.data, byte-identical to the sql-text
-- extension beside it. Edit neither: both are generated by
-- `mimic-utils metrics-finalize` from the finalized attempt.

WITH sofa_filtered AS (
    SELECT
        s.icu_encounter_key,
        s.patient_key,
        s.starttime,
        s.endtime,
        s.respiration_24hours AS respiration,
        s.coagulation_24hours AS coagulation,
        s.liver_24hours AS liver,
        s.cardiovascular_24hours AS cardiovascular,
        s.cns_24hours AS cns,
        s.renal_24hours AS renal,
        s.sofa_24hours AS sofa_score
    FROM sofa AS s
    WHERE s.sofa_24hours >= 2
), s1 AS (
    SELECT
        p.subject_id_str,
        i.stay_id_str,
        soi.ab_id,
        soi.antibiotic,
        soi.antibiotic_time,
        soi.culture_time,
        soi.suspected_infection,
        soi.suspected_infection_time,
        soi.specimen,
        soi.positive_culture,
        sf.starttime,
        sf.endtime,
        sf.respiration,
        sf.coagulation,
        sf.liver,
        sf.cardiovascular,
        sf.cns,
        sf.renal,
        sf.sofa_score,
        soi.patient_key,
        soi.icu_encounter_key,
        sf.sofa_score >= 2 AND soi.suspected_infection = 1 AS sepsis3,
        ROW_NUMBER() OVER (
            PARTITION BY soi.icu_encounter_key
            ORDER BY
                soi.suspected_infection_time,
                soi.antibiotic_time,
                soi.culture_time,
                sf.endtime
        ) AS rn_sus
    FROM suspicion_of_infection AS soi
    INNER JOIN sofa_filtered AS sf
        ON soi.icu_encounter_key = sf.icu_encounter_key
        AND sf.endtime >= soi.suspected_infection_time - INTERVAL 48 HOURS
        AND sf.endtime <= soi.suspected_infection_time + INTERVAL 24 HOURS
    INNER JOIN icu_encounter AS i
        ON soi.icu_encounter_key = i.icu_encounter_key
    INNER JOIN patient AS p
        ON soi.patient_key = p.patient_key
    WHERE soi.icu_encounter_key IS NOT NULL
)
SELECT
    CAST(s.antibiotic_time AS TIMESTAMP_NTZ) AS antibiotic_time,
    CAST(s.culture_time AS TIMESTAMP_NTZ) AS culture_time,
    CAST(s.suspected_infection_time AS TIMESTAMP_NTZ) AS suspected_infection_time,
    CAST(s.endtime AS TIMESTAMP_NTZ) AS sofa_time,
    CAST(s.sofa_score AS INTEGER) AS sofa_score,
    CAST(s.respiration AS INTEGER) AS respiration,
    CAST(s.coagulation AS INTEGER) AS coagulation,
    CAST(s.liver AS INTEGER) AS liver,
    CAST(s.cardiovascular AS INTEGER) AS cardiovascular,
    CAST(s.cns AS INTEGER) AS cns,
    CAST(s.renal AS INTEGER) AS renal,
    CAST(s.sepsis3 AS BOOLEAN) AS sepsis3,
    s.icu_encounter_key AS icu_encounter_key,
    s.patient_key AS patient_key
FROM s1 AS s
WHERE s.rn_sus = 1
;
